namespace BunkFy.Modules.Ingestion.Domain.Errors;

using Gma.Framework.Results;

public static class IngestionDomainErrors
{
    public static readonly Error IdRequired = new("Ingestion.IdRequired", "A non-empty id is required.");
    public static readonly Error ScopeRequired = new("Ingestion.ScopeRequired", "A scope id is required.");
    public static readonly Error PropertyIdRequired = new("Ingestion.PropertyIdRequired", "A property id is required.");
    public static readonly Error ConnectionIdRequired = new("Ingestion.ConnectionIdRequired", "A connection id is required.");
    public static readonly Error AdapterTypeInvalid = new("Ingestion.AdapterTypeInvalid", "The adapter type is invalid.");
    public static readonly Error ExecutionModeInvalid = new("Ingestion.ExecutionModeInvalid", "The adapter execution mode is invalid.");
    public static readonly Error ConflictPolicyInvalid = new("Ingestion.ConflictPolicyInvalid", "The connection conflict policy is invalid.");
    public static readonly Error ConfigurationReferenceInvalid = new("Ingestion.ConfigurationReferenceInvalid", "The configuration reference is invalid.");
    public static readonly Error SecretReferenceInvalid = new("Ingestion.SecretReferenceInvalid", "The secret reference is invalid.");
    public static readonly Error PollingScheduleRequiresPollingMode = new("Ingestion.PollingScheduleRequiresPollingMode", "A polling schedule requires polling execution mode and must be cleared before selecting another mode.");
    public static readonly Error PollingIntervalInvalid = new("Ingestion.PollingIntervalInvalid", "The polling interval must be between one minute and 30 days.");
    public static readonly Error PollingScheduleAttemptsInvalid = new("Ingestion.PollingScheduleAttemptsInvalid", "Polling schedule attempts must be between one and ten.");
    public static readonly Error VersionConflict = new("Ingestion.VersionConflict", "The ingestion record has changed. Refresh and retry.");
    public static readonly Error ConnectionAlreadyEnabled = new("Ingestion.ConnectionAlreadyEnabled", "The adapter connection is already enabled.");
    public static readonly Error ConnectionAlreadyDisabled = new("Ingestion.ConnectionAlreadyDisabled", "The adapter connection is already disabled.");
    public static readonly Error ConnectionNotEnabled = new("Ingestion.ConnectionNotEnabled", "The adapter connection is not enabled.");
    public static readonly Error ConnectionMustBeDisabled = new("Ingestion.ConnectionMustBeDisabled", "The adapter connection must be disabled for this operation.");
    public static readonly Error CheckpointInvalid = new("Ingestion.CheckpointInvalid", "The adapter checkpoint is too long.");
    public static readonly Error IngressCredentialIdentityInvalid = new("Ingestion.IngressCredentialIdentityInvalid", "The adapter ingress credential identity is invalid.");
    public static readonly Error IngressCredentialLabelInvalid = new("Ingestion.IngressCredentialLabelInvalid", "The adapter ingress credential label is invalid.");
    public static readonly Error IngressCredentialSecretInvalid = new("Ingestion.IngressCredentialSecretInvalid", "The adapter ingress credential secret material is invalid.");
    public static readonly Error IngressCredentialExpiryInvalid = new("Ingestion.IngressCredentialExpiryInvalid", "Adapter ingress credentials must expire between five minutes and 366 days after creation.");
    public static readonly Error IngressCredentialActorInvalid = new("Ingestion.IngressCredentialActorInvalid", "A valid adapter ingress credential actor is required.");
    public static readonly Error IngressCredentialAlreadyRevoked = new("Ingestion.IngressCredentialAlreadyRevoked", "The adapter ingress credential is already revoked.");
    public static readonly Error RemoteLeaseIdentityInvalid = new("Ingestion.RemoteLeaseIdentityInvalid", "The remote adapter lease identity is invalid.");
    public static readonly Error RemoteLeaseDurationInvalid = new("Ingestion.RemoteLeaseDurationInvalid", "The remote adapter lease duration is outside the supported bounds.");
    public static readonly Error RemoteLeaseRequiresRemotePollingMode = new("Ingestion.RemoteLeaseRequiresRemotePollingMode", "Remote adapter leases require remote polling execution mode.");
    public static readonly Error RemoteLeaseAlreadyActive = new("Ingestion.RemoteLeaseAlreadyActive", "The adapter connection already has an active remote lease.");
    public static readonly Error RemoteLeaseNotActive = new("Ingestion.RemoteLeaseNotActive", "The remote adapter lease is no longer active.");
    public static readonly Error RemoteLeaseMismatch = new("Ingestion.RemoteLeaseMismatch", "The remote adapter lease proof does not match the current assignment.");
    public static readonly Error RemoteLeaseExpired = new("Ingestion.RemoteLeaseExpired", "The remote adapter lease has expired.");
    public static readonly Error RemoteLeaseMustBeReleased = new("Ingestion.RemoteLeaseMustBeReleased", "Disable the connection before changing an active remote polling mode.");
    public static readonly Error RemoteLeaseEpochExhausted = new("Ingestion.RemoteLeaseEpochExhausted", "The remote adapter lease epoch is exhausted.");
    public static readonly Error TaskExecutionInvalid = new("Ingestion.TaskExecutionInvalid", "The task execution identity is invalid.");
    public static readonly Error RunNotActive = new("Ingestion.RunNotActive", "The adapter run is no longer active.");
    public static readonly Error RunOutcomeInvalid = new("Ingestion.RunOutcomeInvalid", "The adapter run outcome is invalid.");
    public static readonly Error RunCountsInvalid = new("Ingestion.RunCountsInvalid", "Adapter run counts cannot be negative or inconsistent.");
    public static readonly Error ErrorCodeInvalid = new("Ingestion.ErrorCodeInvalid", "The adapter error code is invalid.");
    public static readonly Error ReceiptIdentityInvalid = new("Ingestion.ReceiptIdentityInvalid", "The observation receipt identity is invalid.");
    public static readonly Error PayloadInvalid = new("Ingestion.PayloadInvalid", "The observation payload reference or hash is invalid.");
    public static readonly Error CountryPolicyEvidenceInvalid = new(
        "Ingestion.CountryPolicyEvidenceInvalid",
        "Valid country-policy decision evidence is required for an accepted observation.");
    public static readonly Error RawPayloadRetentionInvalid = new("Ingestion.RawPayloadRetentionInvalid", "The raw payload retention deadline is invalid.");
    public static readonly Error RawPayloadNotPurgeable = new("Ingestion.RawPayloadNotPurgeable", "The raw payload is not terminal and due for purge.");
    public static readonly Error RawPayloadPurgeClaimInvalid = new("Ingestion.RawPayloadPurgeClaimInvalid", "The raw payload purge claim is invalid.");
    public static readonly Error RawPayloadPurgeAlreadyClaimed = new("Ingestion.RawPayloadPurgeAlreadyClaimed", "The raw payload is already claimed by another active purge.");
    public static readonly Error RawPayloadAlreadyPurged = new("Ingestion.RawPayloadAlreadyPurged", "The raw payload has already been purged.");
    public static readonly Error ReprocessingIdentityInvalid = new("Ingestion.ReprocessingIdentityInvalid", "The reprocessing attempt identity is invalid.");
    public static readonly Error ReprocessingParserInvalid = new("Ingestion.ReprocessingParserInvalid", "The reprocessing parser identity is invalid.");
    public static readonly Error ReprocessingRequestInvalid = new("Ingestion.ReprocessingRequestInvalid", "The reprocessing request actor or reservation is invalid.");
    public static readonly Error ReprocessingTaskInvalid = new("Ingestion.ReprocessingTaskInvalid", "The reprocessing task identity or attempt is invalid.");
    public static readonly Error ReprocessingNotActive = new("Ingestion.ReprocessingNotActive", "The reprocessing attempt is no longer active.");
    public static readonly Error ReprocessingReservationActive = new("Ingestion.ReprocessingReservationActive", "Another reprocessing attempt currently reserves the raw payload.");
    public static readonly Error ReprocessingSourceInvalid = new("Ingestion.ReprocessingSourceInvalid", "The source receipt is not eligible for reprocessing.");
    public static readonly Error ReprocessingOutcomeInvalid = new("Ingestion.ReprocessingOutcomeInvalid", "The reprocessing outcome counts are invalid.");
    public static readonly Error ReprocessingErrorInvalid = new("Ingestion.ReprocessingErrorInvalid", "The reprocessing outcome requires a valid error code.");
    public static readonly Error ReceiptNotPending = new("Ingestion.ReceiptNotPending", "The observation receipt is already terminal.");
    public static readonly Error ProposalIdentityInvalid = new("Ingestion.ProposalIdentityInvalid", "The change proposal identity is invalid.");
    public static readonly Error ProposalDiffInvalid = new("Ingestion.ProposalDiffInvalid", "The change proposal diff is invalid.");
    public static readonly Error ProposalReasonCodeInvalid = new("Ingestion.ProposalReasonCodeInvalid", "The change proposal reason code is invalid.");
    public static readonly Error ProposalNotPending = new("Ingestion.ProposalNotPending", "The change proposal is not pending.");
    public static readonly Error ProposalNotApplying = new("Ingestion.ProposalNotApplying", "The change proposal is not being applied.");
    public static readonly Error DecisionReasonInvalid = new("Ingestion.DecisionReasonInvalid", "A valid decision actor and reason are required.");
    public static readonly Error ReservationSourceLinkInvalid = new("Ingestion.ReservationSourceLinkInvalid", "The reservation source link is invalid.");
    public static readonly Error ReservationObservationInvalid = new("Ingestion.ReservationObservationInvalid", "The normalized reservation observation is invalid.");
    public static readonly Error ReservationOperationActive = new("Ingestion.ReservationOperationActive", "A reservation product operation is already active.");
    public static readonly Error ReservationOperationMismatch = new("Ingestion.ReservationOperationMismatch", "The reservation product operation does not match the active source link operation.");
    public static readonly Error ReservationDispatchInvalid = new("Ingestion.ReservationDispatchInvalid", "The reservation dispatch is invalid.");
    public static readonly Error ReservationDispatchNotPending = new("Ingestion.ReservationDispatchNotPending", "The reservation dispatch is already terminal.");
    public static readonly Error SensitiveHistoryRetentionInvalid = new("Ingestion.SensitiveHistoryRetentionInvalid", "The sensitive history retention deadline is invalid.");
    public static readonly Error SensitiveHistoryNotRedactable = new("Ingestion.SensitiveHistoryNotRedactable", "The sensitive history is active or not yet due for redaction.");
    public static readonly Error LegalHoldIdentityInvalid = new("Ingestion.LegalHoldIdentityInvalid", "The legal hold identity is invalid.");
    public static readonly Error LegalHoldReasonInvalid = new("Ingestion.LegalHoldReasonInvalid", "A valid legal hold reason is required.");
    public static readonly Error LegalHoldActorInvalid = new("Ingestion.LegalHoldActorInvalid", "A valid legal hold actor is required.");
    public static readonly Error LegalHoldReleaseReasonInvalid = new("Ingestion.LegalHoldReleaseReasonInvalid", "A valid legal hold release reason is required.");
    public static readonly Error LegalHoldAlreadyReleased = new("Ingestion.LegalHoldAlreadyReleased", "The legal hold is already released.");
    public static readonly Error LegalHoldLifecycleInvalid = new("Ingestion.LegalHoldLifecycleInvalid", "The legal hold lifecycle timestamp is invalid.");
}
