// <auto-generated />
using System;
using BunkFy.Modules.Retention.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BunkFy.Modules.Retention.Persistence.PostgreSqlMigrations.Migrations
{
    [DbContext(typeof(RetentionDbContext))]
    [Migration("20260821172809_AddRetentionScopeProjectionIntegrity")]
    partial class AddRetentionScopeProjectionIntegrity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("retention")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BunkFy.Modules.Retention.Domain.Aggregates.RetentionExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AffectedCount")
                        .HasColumnType("integer");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataClassKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("DeadlineUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExecutionPolicyVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("HoldReviewDueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OutcomeCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RemainingCount")
                        .HasColumnType("integer");

                    b.Property<int?>("ScannedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("TargetKind")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("ScopeId", "Id");

                    b.HasIndex("ScopeId", "State", "CompletedAtUtc");

                    b.HasIndex("ScopeId", "OwnerKey", "DataClassKey", "PropertyId", "ExecutionPolicyVersion", "StartedAtUtc");

                    b.ToTable("executions", "retention", t =>
                        {
                            t.HasCheckConstraint("CK_retention_executions_coordinate", "\"Id\" <> '00000000-0000-0000-0000-000000000000' AND trim(\"ScopeId\") <> '' AND ((\"TargetKind\" = 1 AND \"PropertyId\" IS NULL) OR (\"TargetKind\" = 2 AND \"PropertyId\" IS NOT NULL AND \"PropertyId\" <> '00000000-0000-0000-0000-000000000000'))");

                            t.HasCheckConstraint("CK_retention_executions_keys", "\"OwnerKey\" ~ '^[a-z0-9.-]+$' AND \"DataClassKey\" ~ '^[a-z0-9.-]+$' AND (\"OutcomeCode\" IS NULL OR \"OutcomeCode\" ~ '^[A-Za-z0-9.-]+$')");

                            t.HasCheckConstraint("CK_retention_executions_state", "(\"State\" = 1 AND \"CompletedAtUtc\" IS NULL AND \"ScannedCount\" IS NULL AND \"AffectedCount\" IS NULL AND \"RemainingCount\" IS NULL AND \"OutcomeCode\" IS NULL AND \"HoldReviewDueAtUtc\" IS NULL) OR (\"State\" IN (2, 3, 4) AND \"CompletedAtUtc\" IS NOT NULL AND \"ScannedCount\" >= 0 AND \"AffectedCount\" BETWEEN 0 AND \"ScannedCount\" AND \"RemainingCount\" >= 0 AND length(trim(\"OutcomeCode\")) > 0 AND ((\"State\" = 3 AND \"HoldReviewDueAtUtc\" IS NOT NULL) OR (\"State\" <> 3 AND \"HoldReviewDueAtUtc\" IS NULL)))");

                            t.HasCheckConstraint("CK_retention_executions_time", "\"DeadlineUtc\" > \"StartedAtUtc\" AND (\"CompletedAtUtc\" IS NULL OR \"CompletedAtUtc\" >= \"StartedAtUtc\") AND (\"State\" = 4 OR \"CompletedAtUtc\" IS NULL OR \"CompletedAtUtc\" <= \"DeadlineUtc\")");

                            t.HasCheckConstraint("CK_retention_executions_versions", "\"ExecutionPolicyVersion\" >= 1 AND \"Attempt\" >= 1 AND \"Version\" >= 1 AND (\"State\" = 1 OR \"Version\" >= 2)");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Retention.Domain.Aggregates.RetentionRunRetryRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataClassKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("EvidenceVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("ExecutionPolicyVersion")
                        .HasColumnType("integer");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ScheduledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("TargetKind")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId", "RunId", "EvidenceVersion")
                        .IsUnique();

                    b.HasIndex("ScopeId", "State", "RequestedAtUtc");

                    b.ToTable("run_retry_requests", "retention", t =>
                        {
                            t.HasCheckConstraint("CK_retention_run_retry_request_coordinates", "\"Id\" <> '00000000-0000-0000-0000-000000000000' AND \"RunId\" <> '00000000-0000-0000-0000-000000000000' AND trim(\"ScopeId\") <> '' AND \"OwnerKey\" ~ '^[a-z0-9.-]+$' AND \"DataClassKey\" ~ '^[a-z0-9.-]+$' AND (\"FailureCode\" IS NULL OR \"FailureCode\" ~ '^[a-z0-9.-]+$')");

                            t.HasCheckConstraint("CK_retention_run_retry_request_state", "\"State\" IN (1, 2, 3) AND ((\"State\" = 1 AND \"CompletedAtUtc\" IS NULL AND \"FailureCode\" IS NULL) OR (\"State\" = 2 AND \"CompletedAtUtc\" IS NOT NULL AND \"FailureCode\" IS NULL) OR (\"State\" = 3 AND \"CompletedAtUtc\" IS NOT NULL AND \"FailureCode\" IS NOT NULL))");

                            t.HasCheckConstraint("CK_retention_run_retry_request_target", "(\"TargetKind\" = 1 AND \"PropertyId\" IS NULL) OR (\"TargetKind\" = 2 AND \"PropertyId\" IS NOT NULL AND \"PropertyId\" <> '00000000-0000-0000-0000-000000000000')");

                            t.HasCheckConstraint("CK_retention_run_retry_request_timestamps", "(\"ScheduledAtUtc\" IS NULL OR \"ScheduledAtUtc\" >= \"RequestedAtUtc\") AND (\"CompletedAtUtc\" IS NULL OR \"CompletedAtUtc\" >= \"RequestedAtUtc\")");

                            t.HasCheckConstraint("CK_retention_run_retry_request_versions", "\"ExecutionPolicyVersion\" >= 1 AND \"EvidenceVersion\" >= 1 AND \"Attempt\" >= 1 AND \"Version\" >= 1 AND (\"State\" = 1 OR \"Version\" >= 2)");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Retention.Persistence.RetentionPropertyProjection", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsKnown")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProcessingEnabled")
                        .HasColumnType("boolean");

                    b.Property<long>("PolicySourceVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int?>("RetentionPolicyVersion")
                        .HasColumnType("integer");

                    b.Property<long>("TopologySourceVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("ScopeId", "Id");

                    b.HasIndex("ScopeId", "IsActive", "IsProcessingEnabled", "Id");

                    b.ToTable("property_projection", "retention", t =>
                        {
                            t.HasCheckConstraint("CK_retention_property_projection_coordinates", "\"Id\" <> '00000000-0000-0000-0000-000000000000' AND char_length(\"ScopeId\") > 0 AND \"ScopeId\" = btrim(\"ScopeId\") AND \"ScopeId\" !~ '[[:space:][:cntrl:]]'");

                            t.HasCheckConstraint("CK_retention_property_projection_known", "\"IsKnown\" = (\"TopologySourceVersion\" >= 1 OR \"PolicySourceVersion\" >= 1)");

                            t.HasCheckConstraint("CK_retention_property_projection_policy", "(\"PolicySourceVersion\" = 0 AND \"RetentionPolicyVersion\" IS NULL AND \"IsProcessingEnabled\" = FALSE) OR (\"PolicySourceVersion\" >= 1 AND \"RetentionPolicyVersion\" IS NOT NULL AND \"RetentionPolicyVersion\" >= 1)");

                            t.HasCheckConstraint("CK_retention_property_projection_topology", "(\"TopologySourceVersion\" = 0 AND \"IsActive\" = FALSE) OR \"TopologySourceVersion\" >= 1");

                            t.HasCheckConstraint("CK_retention_property_projection_versions", "\"TopologySourceVersion\" >= 0 AND \"PolicySourceVersion\" >= 0");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Retention.Persistence.RetentionScheduleState", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OwnerKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DataClassKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TargetKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ExecutionPolicyVersion")
                        .HasColumnType("integer");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("HoldReviewDueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastAffectedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastExecutionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("LastRemainingCount")
                        .HasColumnType("integer");

                    b.Property<int?>("LastScannedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NextDueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OutcomeCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("ScopeId", "OwnerKey", "DataClassKey", "TargetKey", "ExecutionPolicyVersion");

                    b.HasIndex("ScopeId", "HoldReviewDueAtUtc");

                    b.HasIndex("ScopeId", "LastExecutionId")
                        .IsUnique();

                    b.HasIndex("ScopeId", "State", "NextDueAtUtc");

                    b.ToTable("schedule_state", "retention", t =>
                        {
                            t.HasCheckConstraint("CK_retention_schedule_state_coordinates", "trim(\"ScopeId\") <> '' AND \"LastExecutionId\" <> '00000000-0000-0000-0000-000000000000' AND \"OwnerKey\" ~ '^[a-z0-9.-]+$' AND \"DataClassKey\" ~ '^[a-z0-9.-]+$' AND (\"OutcomeCode\" IS NULL OR \"OutcomeCode\" ~ '^[A-Za-z0-9.-]+$')");

                            t.HasCheckConstraint("CK_retention_schedule_state_result", "(\"State\" = 1 AND \"LastCompletedAtUtc\" IS NULL AND \"LastScannedCount\" IS NULL AND \"LastAffectedCount\" IS NULL AND \"LastRemainingCount\" IS NULL AND \"OutcomeCode\" IS NULL AND \"HoldReviewDueAtUtc\" IS NULL) OR (\"State\" = 2 AND \"LastCompletedAtUtc\" IS NOT NULL AND \"LastScannedCount\" >= 0 AND \"LastAffectedCount\" BETWEEN 0 AND \"LastScannedCount\" AND \"LastRemainingCount\" >= 0 AND \"OutcomeCode\" IS NOT NULL AND \"HoldReviewDueAtUtc\" IS NULL AND \"ConsecutiveFailures\" = 0) OR (\"State\" = 3 AND \"LastCompletedAtUtc\" IS NOT NULL AND \"LastScannedCount\" >= 0 AND \"LastAffectedCount\" BETWEEN 0 AND \"LastScannedCount\" AND \"LastRemainingCount\" >= 0 AND \"OutcomeCode\" IS NOT NULL AND \"HoldReviewDueAtUtc\" IS NOT NULL AND \"ConsecutiveFailures\" = 0) OR (\"State\" = 4 AND \"LastCompletedAtUtc\" IS NOT NULL AND \"LastScannedCount\" >= 0 AND \"LastAffectedCount\" BETWEEN 0 AND \"LastScannedCount\" AND \"LastRemainingCount\" >= 0 AND \"OutcomeCode\" IS NOT NULL AND \"HoldReviewDueAtUtc\" IS NULL AND \"ConsecutiveFailures\" >= 1)");

                            t.HasCheckConstraint("CK_retention_schedule_state_target", "(\"TargetKey\" = 'tenant' AND \"PropertyId\" IS NULL) OR (\"PropertyId\" IS NOT NULL AND \"PropertyId\" <> '00000000-0000-0000-0000-000000000000' AND \"TargetKey\" = replace(\"PropertyId\"::text, '-', ''))");

                            t.HasCheckConstraint("CK_retention_schedule_state_time", "\"NextDueAtUtc\" > \"LastStartedAtUtc\" AND (\"LastCompletedAtUtc\" IS NULL OR \"LastCompletedAtUtc\" >= \"LastStartedAtUtc\")");

                            t.HasCheckConstraint("CK_retention_schedule_state_versions", "\"ExecutionPolicyVersion\" >= 1 AND \"Version\" >= 1 AND \"ConsecutiveFailures\" >= 0 AND (\"State\" = 1 OR \"Version\" >= 2)");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Retention.Persistence.RetentionTenantProjection", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<long>("SourceVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("ScopeId");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.HasIndex("IsActive", "ScopeId");

                    b.ToTable("tenant_projection", "retention", t =>
                        {
                            t.HasCheckConstraint("CK_retention_tenant_projection_coordinates", "\"OrganizationId\" <> '00000000-0000-0000-0000-000000000000' AND char_length(\"ScopeId\") > 0 AND \"ScopeId\" = btrim(\"ScopeId\") AND \"ScopeId\" !~ '[[:space:][:cntrl:]]'");

                            t.HasCheckConstraint("CK_retention_tenant_projection_version", "\"SourceVersion\" >= 1");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Retention.Persistence.RetentionTenantRevision", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("DestroyCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DestroyOperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestroyRequestSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("DestroyStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LifecycleStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("ScopeId");

                    b.ToTable("tenant_revisions", "retention", t =>
                        {
                            t.HasCheckConstraint("CK_retention_tenant_revision_lifecycle", "(\"LifecycleStatus\" = 1 AND \"DestroyOperationId\" IS NULL AND \"DestroyRequestSha256\" IS NULL AND \"DestroyStartedAtUtc\" IS NULL AND \"DestroyCompletedAtUtc\" IS NULL) OR (\"LifecycleStatus\" = 2 AND \"DestroyOperationId\" IS NOT NULL AND \"DestroyRequestSha256\" IS NOT NULL AND \"DestroyStartedAtUtc\" IS NOT NULL AND \"DestroyCompletedAtUtc\" IS NULL) OR (\"LifecycleStatus\" = 3 AND \"DestroyOperationId\" IS NOT NULL AND \"DestroyRequestSha256\" IS NOT NULL AND \"DestroyStartedAtUtc\" IS NOT NULL AND \"DestroyCompletedAtUtc\" >= \"DestroyStartedAtUtc\")");

                            t.HasCheckConstraint("CK_retention_tenant_revision_positive", "\"Revision\" > 0");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Retention.Persistence.TenantTermination.RetentionTenantDestroyOperation", b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<int>("BatchSize")
                        .HasColumnType("integer");

                    b.Property<int>("CompletedBatchCount")
                        .HasColumnType("integer");

                    b.Property<int>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<int>("ProofVersion")
                        .HasColumnType("integer");

                    b.Property<string>("RemovalProofSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<long>("RemovedRecordCount")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<long>("ResultingRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("SelectedRevision")
                        .HasColumnType("bigint");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OperationId");

                    b.HasIndex("ScopeId")
                        .IsUnique();

                    b.ToTable("tenant_destroy_operations", "retention", t =>
                        {
                            t.HasCheckConstraint("CK_retention_tenant_destroy_operation_batch", "\"BatchSize\" BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_retention_tenant_destroy_operation_progress", "\"Stage\" BETWEEN 1 AND 8 AND \"RemovedRecordCount\" >= 0 AND \"CompletedBatchCount\" >= 0 AND \"ProofVersion\" = 1 AND \"ConcurrencyVersion\" >= 1");

                            t.HasCheckConstraint("CK_retention_tenant_destroy_operation_revisions", "\"SelectedRevision\" >= 0 AND \"ResultingRevision\" = \"SelectedRevision\" + 1");

                            t.HasCheckConstraint("CK_retention_tenant_destroy_operation_times", "\"UpdatedAtUtc\" >= \"StartedAtUtc\"");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Retention.Persistence.TenantTermination.RetentionTenantDestroyReceipt", b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<int>("BatchSize")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompletedBatchCount")
                        .HasColumnType("integer");

                    b.Property<string>("RemovalProofSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<int>("RemovalProofVersion")
                        .HasColumnType("integer");

                    b.Property<long>("RemovedRecordCount")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<long>("ResultingRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("SelectedRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OperationId");

                    b.HasIndex("ScopeId")
                        .IsUnique();

                    b.ToTable("tenant_destroy_receipts", "retention", t =>
                        {
                            t.HasCheckConstraint("CK_retention_tenant_destroy_receipt_progress", "((\"RemovedRecordCount\" = 0 AND \"CompletedBatchCount\" = 0) OR (\"RemovedRecordCount\" > 0 AND \"CompletedBatchCount\" > 0)) AND \"BatchSize\" BETWEEN 1 AND 500 AND \"RemovalProofVersion\" = 1");

                            t.HasCheckConstraint("CK_retention_tenant_destroy_receipt_revisions", "\"SelectedRevision\" >= 0 AND \"ResultingRevision\" = \"SelectedRevision\" + 1");

                            t.HasCheckConstraint("CK_retention_tenant_destroy_receipt_times", "\"CompletedAtUtc\" >= \"StartedAtUtc\"");
                        });
                });

            modelBuilder.Entity("Gma.Framework.Messaging.Infrastructure.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Handler")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessingStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ScopeId");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id", "Handler");

                    b.HasIndex("Handler", "Status");

                    b.HasIndex("Status", "ProcessedAtUtc");

                    b.ToTable("inbox_messages", "retention");
                });

            modelBuilder.Entity("Gma.Framework.Messaging.Infrastructure.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ScopeId");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "NextAttemptAtUtc", "LockedUntilUtc", "CreatedAtUtc");

                    b.ToTable("outbox_messages", "retention");
                });
#pragma warning restore 612, 618
        }
    }
}
