// <auto-generated />
using System;
using BunkFy.Modules.Retention.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BunkFy.Modules.Retention.Persistence.PostgreSqlMigrations.Migrations
{
    [DbContext(typeof(RetentionDbContext))]
    partial class RetentionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("retention")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BunkFy.Modules.Retention.Domain.Aggregates.RetentionExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AffectedCount")
                        .HasColumnType("integer");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataClassKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("DeadlineUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExecutionPolicyVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("HoldReviewDueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OutcomeCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RemainingCount")
                        .HasColumnType("integer");

                    b.Property<int?>("ScannedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("TargetKind")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("ScopeId", "Id");

                    b.HasIndex("ScopeId", "State", "CompletedAtUtc");

                    b.HasIndex("ScopeId", "OwnerKey", "DataClassKey", "PropertyId", "ExecutionPolicyVersion", "StartedAtUtc");

                    b.ToTable("executions", "retention", t =>
                        {
                            t.HasCheckConstraint("CK_retention_executions_coordinate", "(\"TargetKind\" = 1 AND \"PropertyId\" IS NULL) OR (\"TargetKind\" = 2 AND \"PropertyId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_retention_executions_state", "(\"State\" = 1 AND \"CompletedAtUtc\" IS NULL AND \"ScannedCount\" IS NULL AND \"AffectedCount\" IS NULL AND \"RemainingCount\" IS NULL AND \"OutcomeCode\" IS NULL AND \"HoldReviewDueAtUtc\" IS NULL) OR (\"State\" IN (2, 3, 4) AND \"CompletedAtUtc\" IS NOT NULL AND \"ScannedCount\" >= 0 AND \"AffectedCount\" BETWEEN 0 AND \"ScannedCount\" AND \"RemainingCount\" >= 0 AND length(trim(\"OutcomeCode\")) > 0 AND ((\"State\" = 3 AND \"HoldReviewDueAtUtc\" IS NOT NULL) OR (\"State\" <> 3 AND \"HoldReviewDueAtUtc\" IS NULL)))");

                            t.HasCheckConstraint("CK_retention_executions_time", "\"DeadlineUtc\" > \"StartedAtUtc\"");

                            t.HasCheckConstraint("CK_retention_executions_versions", "\"ExecutionPolicyVersion\" >= 1 AND \"Attempt\" >= 1 AND \"Version\" >= 1");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Retention.Persistence.RetentionPropertyProjection", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsKnown")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProcessingEnabled")
                        .HasColumnType("boolean");

                    b.Property<long>("PolicySourceVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int?>("RetentionPolicyVersion")
                        .HasColumnType("integer");

                    b.Property<long>("TopologySourceVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("ScopeId", "Id");

                    b.HasIndex("ScopeId", "IsActive", "IsProcessingEnabled", "Id");

                    b.ToTable("property_projection", "retention", t =>
                        {
                            t.HasCheckConstraint("CK_retention_property_projection_policy", "(\"PolicySourceVersion\" = 0 AND \"RetentionPolicyVersion\" IS NULL AND \"IsProcessingEnabled\" = FALSE) OR (\"PolicySourceVersion\" >= 1 AND \"RetentionPolicyVersion\" >= 1)");

                            t.HasCheckConstraint("CK_retention_property_projection_versions", "\"TopologySourceVersion\" >= 0 AND \"PolicySourceVersion\" >= 0");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Retention.Persistence.RetentionScheduleState", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OwnerKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DataClassKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TargetKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ExecutionPolicyVersion")
                        .HasColumnType("integer");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("HoldReviewDueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastAffectedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastExecutionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("LastRemainingCount")
                        .HasColumnType("integer");

                    b.Property<int?>("LastScannedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NextDueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OutcomeCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("ScopeId", "OwnerKey", "DataClassKey", "TargetKey", "ExecutionPolicyVersion");

                    b.HasIndex("ScopeId", "HoldReviewDueAtUtc");

                    b.HasIndex("ScopeId", "State", "NextDueAtUtc");

                    b.ToTable("schedule_state", "retention", t =>
                        {
                            t.HasCheckConstraint("CK_retention_schedule_state_result", "\"State\" IN (1, 2, 3, 4) AND ((\"LastCompletedAtUtc\" IS NULL AND \"LastScannedCount\" IS NULL AND \"LastAffectedCount\" IS NULL AND \"LastRemainingCount\" IS NULL AND \"OutcomeCode\" IS NULL) OR (\"LastCompletedAtUtc\" IS NOT NULL AND \"LastScannedCount\" >= 0 AND \"LastAffectedCount\" BETWEEN 0 AND \"LastScannedCount\" AND \"LastRemainingCount\" >= 0 AND length(trim(\"OutcomeCode\")) > 0))");

                            t.HasCheckConstraint("CK_retention_schedule_state_target", "(\"TargetKey\" = 'tenant' AND \"PropertyId\" IS NULL) OR (char_length(\"TargetKey\") = 32 AND \"PropertyId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_retention_schedule_state_time", "\"NextDueAtUtc\" > \"LastStartedAtUtc\" AND (\"LastCompletedAtUtc\" IS NULL OR \"LastCompletedAtUtc\" >= \"LastStartedAtUtc\")");

                            t.HasCheckConstraint("CK_retention_schedule_state_versions", "\"ExecutionPolicyVersion\" >= 1 AND \"Version\" >= 1 AND \"ConsecutiveFailures\" >= 0");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Retention.Persistence.RetentionTenantProjection", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<long>("SourceVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("ScopeId");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.HasIndex("IsActive", "ScopeId");

                    b.ToTable("tenant_projection", "retention", t =>
                        {
                            t.HasCheckConstraint("CK_retention_tenant_projection_version", "\"SourceVersion\" >= 1");
                        });
                });

            modelBuilder.Entity("Gma.Framework.Messaging.Infrastructure.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Handler")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessingStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ScopeId");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id", "Handler");

                    b.HasIndex("Handler", "Status");

                    b.HasIndex("Status", "ProcessedAtUtc");

                    b.ToTable("inbox_messages", "retention");
                });
#pragma warning restore 612, 618
        }
    }
}
