// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using BunkFy.Modules.Reservations.Persistence;

#nullable disable

namespace BunkFy.Modules.Reservations.Persistence.PostgreSqlMigrations.Migrations
{
    [DbContext(typeof(ReservationsDbContext))]
    [Migration("20260712155149_AddGuestUnlinkSnapshot")]
    partial class AddGuestUnlinkSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reservations")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gma.Framework.Messaging.Infrastructure.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Handler")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessingStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ScopeId");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id", "Handler");

                    b.HasIndex("Handler", "Status");

                    b.ToTable("inbox_messages", "reservations");
                });

            modelBuilder.Entity("Gma.Framework.Messaging.Infrastructure.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ScopeId");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "NextAttemptAtUtc", "LockedUntilUtc", "CreatedAtUtc");

                    b.ToTable("outbox_messages", "reservations");
                });

            modelBuilder.Entity("BunkFy.Modules.Reservations.Domain.Aggregates.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AllocationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("AllocationRejection")
                        .HasColumnType("integer");

                    b.Property<Guid>("AllocationRequestId")
                        .HasColumnType("uuid");

                    b.Property<long?>("AllocationVersion")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Arrival")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("CheckedInAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("CheckedInBusinessDate")
                        .HasColumnType("date");

                    b.Property<string>("CheckedInBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("CheckedOutAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("CheckedOutBusinessDate")
                        .HasColumnType("date");

                    b.Property<string>("CheckedOutBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Departure")
                        .HasColumnType("date");

                    b.Property<long>("DetailsRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer");

                    b.Property<int?>("LastAllocationAmendmentRejectionCode")
                        .HasColumnType("integer");

                    b.Property<string>("LastDetailsActorId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("LastDetailsAdapterConnectionId")
                        .HasColumnType("uuid");

                    b.Property<int>("LastDetailsChangeOrigin")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastDetailsChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastDetailsExternalOperationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("LastReleaseRejectionCode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("NoShowAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("NoShowBusinessDate")
                        .HasColumnType("date");

                    b.Property<string>("NoShowBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("PendingAllocationAmendmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("PendingAllocationAmendmentRequestFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<DateOnly?>("PendingArrival")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PendingDeparture")
                        .HasColumnType("date");

                    b.Property<string>("PendingDetailsActorId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PendingDetailsAdapterConnectionId")
                        .HasColumnType("uuid");

                    b.Property<int>("PendingDetailsChangeOrigin")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PendingDetailsCorrelationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PendingDetailsExternalOperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PendingEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int?>("PendingGuestCount")
                        .HasColumnType("integer");

                    b.Property<string>("PendingInventoryUnitIds")
                        .HasMaxLength(3300)
                        .HasColumnType("character varying(3300)");

                    b.Property<string>("PendingNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PendingPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PendingPrimaryGuestName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PendingStayActorId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("PendingStayBusinessDate")
                        .HasColumnType("date");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PrimaryGuestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("ProjectionOrdinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProjectionOrdinal"));

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReleaseRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProjectionOrdinal")
                        .IsUnique();

                    b.HasIndex("ScopeId", "AllocationRequestId")
                        .IsUnique();

                    b.HasIndex("ScopeId", "SourceSystem", "SourceReference")
                        .IsUnique();

                    b.HasIndex("ScopeId", "PropertyId", "Status", "Arrival", "Departure");

                    b.ToTable("reservations", "reservations", t =>
                        {
                            t.HasCheckConstraint("CK_reservations_checked_in_complete", "(\"Status\" IN (6, 9, 10) AND \"CheckedInBusinessDate\" IS NOT NULL AND \"CheckedInAtUtc\" IS NOT NULL AND \"CheckedInBy\" IS NOT NULL AND length(trim(\"CheckedInBy\")) > 0) OR (\"Status\" NOT IN (6, 9, 10) AND \"CheckedInBusinessDate\" IS NULL AND \"CheckedInAtUtc\" IS NULL AND \"CheckedInBy\" IS NULL)");

                            t.HasCheckConstraint("CK_reservations_checked_out_complete", "(\"Status\" = 10 AND \"CheckedOutBusinessDate\" IS NOT NULL AND \"CheckedOutAtUtc\" IS NOT NULL AND \"CheckedOutBy\" IS NOT NULL AND length(trim(\"CheckedOutBy\")) > 0) OR (\"Status\" <> 10 AND \"CheckedOutBusinessDate\" IS NULL AND \"CheckedOutAtUtc\" IS NULL AND \"CheckedOutBy\" IS NULL)");

                            t.HasCheckConstraint("CK_reservations_no_show_complete", "(\"Status\" = 8 AND \"NoShowBusinessDate\" IS NOT NULL AND \"NoShowAtUtc\" IS NOT NULL AND \"NoShowBy\" IS NOT NULL AND length(trim(\"NoShowBy\")) > 0) OR (\"Status\" <> 8 AND \"NoShowBusinessDate\" IS NULL AND \"NoShowAtUtc\" IS NULL AND \"NoShowBy\" IS NULL)");

                            t.HasCheckConstraint("CK_reservations_pending_stay_complete", "(\"Status\" IN (7, 9) AND \"PendingStayBusinessDate\" IS NOT NULL AND \"PendingStayActorId\" IS NOT NULL AND length(trim(\"PendingStayActorId\")) > 0 AND \"ReleaseRequestId\" IS NOT NULL) OR (\"Status\" NOT IN (7, 9) AND \"PendingStayBusinessDate\" IS NULL AND \"PendingStayActorId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Reservations.Domain.Entities.RequestedInventoryUnit", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("ScopeId", "ReservationId", "Id");

                    b.HasIndex("ScopeId", "Id", "ReservationId");

                    b.ToTable("requested_inventory_units", "reservations");
                });

            modelBuilder.Entity("BunkFy.Modules.Reservations.Domain.Entities.ReservationGuest", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<long>("LinkVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LinkedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("UnlinkedArrival")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("UnlinkedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UnlinkedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("UnlinkedCheckedInBusinessDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("UnlinkedCheckedOutBusinessDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("UnlinkedDeparture")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("UnlinkedNoShowBusinessDate")
                        .HasColumnType("date");

                    b.Property<int?>("UnlinkedReservationStatus")
                        .HasColumnType("integer");

                    b.HasKey("ScopeId", "ReservationId", "Id");

                    b.HasIndex("ScopeId", "Id", "ReservationId");

                    b.HasIndex("ScopeId", "ReservationId", "IsCurrent", "Role");

                    b.ToTable("reservation_guests", "reservations", t =>
                        {
                            t.HasCheckConstraint("CK_reservation_guests_link_version", "\"LinkVersion\" >= 1");

                            t.HasCheckConstraint("CK_reservation_guests_unlink_snapshot", "(\"IsCurrent\" = TRUE AND \"UnlinkedBy\" IS NULL AND \"UnlinkedAtUtc\" IS NULL AND \"UnlinkedArrival\" IS NULL AND \"UnlinkedDeparture\" IS NULL AND \"UnlinkedReservationStatus\" IS NULL) OR (\"IsCurrent\" = FALSE AND \"UnlinkedBy\" IS NOT NULL AND \"UnlinkedAtUtc\" IS NOT NULL AND \"UnlinkedArrival\" IS NOT NULL AND \"UnlinkedDeparture\" IS NOT NULL AND \"UnlinkedReservationStatus\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Reservations.Persistence.ReservationDetailsHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("AdapterConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("AfterSnapshotHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AfterSnapshotJson")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("character varying(32768)");

                    b.Property<string>("BeforeSnapshotJson")
                        .HasMaxLength(32768)
                        .HasColumnType("character varying(32768)");

                    b.Property<string>("ChangedFieldsJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExternalOperationId")
                        .HasColumnType("uuid");

                    b.Property<long>("FromRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperationDeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Origin")
                        .HasColumnType("integer");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ToRevision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId", "OperationDeduplicationKey")
                        .IsUnique();

                    b.HasIndex("ScopeId", "PropertyId", "OccurredAtUtc");

                    b.HasIndex("ScopeId", "ReservationId", "ToRevision")
                        .IsUnique();

                    b.ToTable("reservation_details_history", "reservations");
                });

            modelBuilder.Entity("BunkFy.Modules.Reservations.Persistence.ReservationExternalOperation", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<long?>("DetailsRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<long?>("ReservationVersion")
                        .HasColumnType("bigint");

                    b.HasKey("ScopeId", "Id");

                    b.HasIndex("ScopeId", "ReceiptId");

                    b.HasIndex("ScopeId", "ConnectionId", "CompletedAtUtc");

                    b.ToTable("external_operations", "reservations");
                });

            modelBuilder.Entity("BunkFy.Modules.Reservations.Persistence.ReservationGuestProfileProjection", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OriginPropertyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("ScopeId", "Id");

                    b.HasIndex("ScopeId", "OriginPropertyId", "Status", "Id");

                    b.ToTable("guest_profile_projection", "reservations", t =>
                        {
                            t.HasCheckConstraint("CK_reservations_guest_profile_projection_version", "\"Version\" >= 1");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Reservations.Persistence.ReservationInventoryAllocationProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("Arrival")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("Departure")
                        .HasColumnType("date");

                    b.Property<bool>("IsKnown")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId", "PropertyId", "Status", "Arrival", "Departure");

                    b.ToTable("inventory_allocation_projections", "reservations");
                });

            modelBuilder.Entity("BunkFy.Modules.Reservations.Persistence.ReservationInventoryAllocationUnitProjection", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("AllocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("ScopeId", "AllocationId", "Id");

                    b.HasIndex("ScopeId", "Id", "AllocationId");

                    b.ToTable("inventory_allocation_unit_projections", "reservations");
                });

            modelBuilder.Entity("BunkFy.Modules.Reservations.Persistence.ReservationInventoryBlockProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("Arrival")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("Departure")
                        .HasColumnType("date");

                    b.Property<Guid>("InventoryUnitId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsKnown")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("ScopeId", "Id");

                    b.HasIndex("ScopeId", "PropertyId", "InventoryUnitId", "Status", "Arrival", "Departure");

                    b.ToTable("inventory_block_projections", "reservations");
                });

            modelBuilder.Entity("BunkFy.Modules.Reservations.Persistence.ReservationInventoryUnitProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BedId")
                        .HasColumnType("uuid");

                    b.Property<long>("ConfigurationVersion")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsSellable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTopologyActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("UnitVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("ScopeId", "Id");

                    b.HasIndex("ScopeId", "PropertyId", "RoomId", "IsSellable");

                    b.ToTable("inventory_unit_projections", "reservations");
                });

            modelBuilder.Entity("BunkFy.Modules.Reservations.Persistence.ReservationsProjectionRebuildCheckpoint", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProjectionName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cursor")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("FailedCount")
                        .HasColumnType("bigint");

                    b.Property<long>("ProcessedCount")
                        .HasColumnType("bigint");

                    b.Property<int>("ProjectionVersion")
                        .HasColumnType("integer");

                    b.Property<long>("SkippedCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("WrittenCount")
                        .HasColumnType("bigint");

                    b.HasKey("ScopeId", "ProjectionName", "RunId");

                    b.ToTable("projection_rebuild_checkpoints", "reservations");
                });

            modelBuilder.Entity("BunkFy.Modules.Reservations.Domain.Entities.RequestedInventoryUnit", b =>
                {
                    b.HasOne("BunkFy.Modules.Reservations.Domain.Aggregates.Reservation", null)
                        .WithMany("RequestedUnits")
                        .HasForeignKey("ScopeId", "ReservationId")
                        .HasPrincipalKey("ScopeId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BunkFy.Modules.Reservations.Domain.Entities.ReservationGuest", b =>
                {
                    b.HasOne("BunkFy.Modules.Reservations.Domain.Aggregates.Reservation", null)
                        .WithMany("Guests")
                        .HasForeignKey("ScopeId", "ReservationId")
                        .HasPrincipalKey("ScopeId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BunkFy.Modules.Reservations.Persistence.ReservationInventoryAllocationUnitProjection", b =>
                {
                    b.HasOne("BunkFy.Modules.Reservations.Persistence.ReservationInventoryAllocationProjection", null)
                        .WithMany("Units")
                        .HasForeignKey("ScopeId", "AllocationId")
                        .HasPrincipalKey("ScopeId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BunkFy.Modules.Reservations.Domain.Aggregates.Reservation", b =>
                {
                    b.Navigation("Guests");

                    b.Navigation("RequestedUnits");
                });

            modelBuilder.Entity("BunkFy.Modules.Reservations.Persistence.ReservationInventoryAllocationProjection", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
