namespace BunkFy.Modules.DataRights.Contracts;

public sealed record DataRightsExecutionWorkItemDto(
    Guid Id,
    Guid BatchId,
    Guid CaseId,
    Guid? PropertyId,
    long ApprovalRevision,
    long ExecutionRevision,
    DataRightsOperation Operation,
    string OwnerKey,
    string RecordType,
    Guid RecordId,
    long SelectedRecordVersion,
    int PolicyEvidenceSchemaVersion,
    string PolicyId,
    int PolicyVersion,
    string RetentionPolicyId,
    int RetentionPolicyVersion,
    string PolicyContentSha256,
    int OwnerContractVersion,
    DataRightsExecutionWorkItemStatus Status,
    int AttemptCount,
    Guid? TaskRunId,
    int LastTaskAttempt,
    DateTimeOffset? LastAttemptAtUtc,
    int? OwnerReceiptContractVersion,
    Guid? OwnerReceiptId,
    long? ResultingRecordVersion,
    string? OwnerDispositionCode,
    string? OwnerReasonCode,
    string? OwnerReceiptSha256,
    DateTimeOffset? OwnerCompletedAtUtc,
    string? OutcomeCode,
    DateTimeOffset? OutcomeAtUtc,
    DateTimeOffset CreatedAtUtc,
    long Version,
    DataRightsCaseType CaseType = DataRightsCaseType.GuestRights,
    DataRightsExecutionScopeKind ScopeKind =
        DataRightsExecutionScopeKind.Property,
    string? PolicyPurposeCode = null,
    string? PolicySurface = null,
    string? PolicySourceProvenance = null,
    string? PolicyRetentionDataClass = null,
    string? PolicyRetentionTrigger = null,
    DateTimeOffset? PolicyRetentionTriggeredAtUtc = null,
    DateTimeOffset? PolicyRetentionDeadlineUtc = null,
    DateTimeOffset? PolicyEvaluatedAtUtc = null,
    string? PolicyStateBindingsSha256 = null,
    long? PolicyPropertyVersion = null,
    string? PolicyOperatingCountryCode = null,
    bool? PolicyRequiresDistinctExecutor = null);
