// <auto-generated />
using System;
using BunkFy.Modules.Inventory.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BunkFy.Modules.Inventory.Persistence.PostgreSqlMigrations.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260726231750_AddInventoryAllocationAnonymisationOwnerProof")]
    partial class AddInventoryAllocationAnonymisationOwnerProof
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BunkFy.Modules.Inventory.Domain.Aggregates.BedRetirementProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BedId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("RejectionReasonCode")
                        .HasColumnType("integer");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId", "BedId")
                        .IsUnique();

                    b.HasIndex("ScopeId", "PropertyId", "RoomId", "State");

                    b.ToTable("bed_retirements", "inventory");
                });

            modelBuilder.Entity("BunkFy.Modules.Inventory.Domain.Aggregates.InventoryAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllocationRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AnonymisedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Arrival")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Departure")
                        .HasColumnType("date");

                    b.Property<bool>("IsAnonymised")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rejection")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ReleaseRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId", "AllocationRequestId")
                        .IsUnique();

                    b.HasIndex("ScopeId", "ReservationId")
                        .IsUnique();

                    b.HasIndex("ScopeId", "PropertyId", "Status", "Arrival", "Departure");

                    b.ToTable("allocations", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_allocations_anonymisation_state", "(\"IsAnonymised\" = TRUE AND \"AnonymisedAtUtc\" IS NOT NULL) OR (\"IsAnonymised\" = FALSE AND \"AnonymisedAtUtc\" IS NULL)");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Inventory.Domain.Aggregates.ManualInventoryBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Arrival")
                        .HasColumnType("date");

                    b.Property<Guid>("BlockGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Departure")
                        .HasColumnType("date");

                    b.Property<Guid>("InventoryUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId", "InventoryUnitId");

                    b.HasIndex("ScopeId", "PropertyId", "BlockGroupId", "Status");

                    b.HasIndex("ScopeId", "PropertyId", "InventoryUnitId", "Status", "Arrival", "Departure");

                    b.ToTable("manual_blocks", "inventory");
                });

            modelBuilder.Entity("BunkFy.Modules.Inventory.Domain.Aggregates.RoomInventoryConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AvailabilityMutationVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<int>("SalesMode")
                        .HasColumnType("integer");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId", "PropertyId");

                    b.ToTable("room_configurations", "inventory");
                });

            modelBuilder.Entity("BunkFy.Modules.Inventory.Domain.Aggregates.RoomRetirementProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("RejectionReasonCode")
                        .HasColumnType("integer");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId", "RoomId")
                        .IsUnique();

                    b.HasIndex("ScopeId", "PropertyId", "State");

                    b.ToTable("room_retirements", "inventory");
                });

            modelBuilder.Entity("BunkFy.Modules.Inventory.Domain.DataRights.InventoryAllocationAnonymisationReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("AllocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalEvidenceSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<long>("ApprovalRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("CanonicalSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Disposition")
                        .HasColumnType("integer");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid");

                    b.Property<long>("OperationRevision")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<int>("RemovedAmendmentDecisionCount")
                        .HasColumnType("integer");

                    b.Property<long>("ResultingAllocationVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ResultingReservationPseudonym")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("SelectedAllocationVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasAlternateKey("ScopeId", "CanonicalSha256");

                    b.HasAlternateKey("ScopeId", "Id");

                    b.HasIndex("ScopeId", "AllocationId");

                    b.HasIndex("ScopeId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ScopeId", "PropertyId", "AllocationId", "ResultingAllocationVersion")
                        .IsUnique();

                    b.HasIndex("ScopeId", "CaseId", "ApprovalRevision", "OperationRevision", "AllocationId")
                        .IsUnique();

                    b.ToTable("allocation_anonymisation_receipts", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_allocation_anonymisation_receipts_actor", "length(trim(\"ActorId\")) > 0");

                            t.HasCheckConstraint("CK_allocation_anonymisation_receipts_contract", "\"ContractVersion\" = 1");

                            t.HasCheckConstraint("CK_allocation_anonymisation_receipts_counts", "\"RemovedAmendmentDecisionCount\" >= 0");

                            t.HasCheckConstraint("CK_allocation_anonymisation_receipts_digests", "char_length(\"ApprovalEvidenceSha256\") = 64 AND char_length(\"CanonicalSha256\") = 64");

                            t.HasCheckConstraint("CK_allocation_anonymisation_receipts_outcome", "\"Disposition\" = 1 AND \"Reason\" = 1");

                            t.HasCheckConstraint("CK_allocation_anonymisation_receipts_revisions", "\"ApprovalRevision\" >= 1 AND \"OperationRevision\" > \"ApprovalRevision\"");

                            t.HasCheckConstraint("CK_allocation_anonymisation_receipts_versions", "\"SelectedAllocationVersion\" >= 1 AND \"ResultingAllocationVersion\" = \"SelectedAllocationVersion\" + 1");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Inventory.Domain.DataRights.InventoryAllocationAnonymisationRestoreReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllocationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllocationPresent")
                        .HasColumnType("boolean");

                    b.Property<string>("CanonicalSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("LedgerEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("LedgerEntrySha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("OriginallyCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OwnerReceiptContractVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerReceiptId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerReceiptSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ReplayedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ResultingAllocationVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ResultingReservationPseudonym")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("TenantSequence")
                        .HasColumnType("bigint");

                    b.Property<long>("TombstoneRevision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("ScopeId", "Id");

                    b.HasIndex("ScopeId", "AllocationId");

                    b.HasIndex("ScopeId", "PropertyId", "AllocationId", "LedgerEntryId")
                        .IsUnique();

                    b.ToTable("allocation_anonymisation_restore_receipts", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_allocation_anonymisation_restore_receipts_contract", "\"ContractVersion\" = 1");

                            t.HasCheckConstraint("CK_allocation_anonymisation_restore_receipts_coordinates", "\"TenantSequence\" >= 1 AND \"OwnerReceiptContractVersion\" >= 1 AND \"ResultingAllocationVersion\" >= 1 AND \"TombstoneRevision\" >= 1");

                            t.HasCheckConstraint("CK_allocation_anonymisation_restore_receipts_digests", "char_length(\"LedgerEntrySha256\") = 64 AND char_length(\"OwnerReceiptSha256\") = 64 AND char_length(\"CanonicalSha256\") = 64");

                            t.HasCheckConstraint("CK_allocation_anonymisation_restore_receipts_identity", "\"LedgerEntryId\" = \"Id\"");

                            t.HasCheckConstraint("CK_allocation_anonymisation_restore_receipts_times", "\"ReplayedAtUtc\" >= \"OriginallyCompletedAtUtc\"");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Inventory.Domain.DataRights.InventoryAllocationAnonymisationTombstone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllocationPresent")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastReplayedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LedgerEntryId")
                        .HasColumnType("uuid");

                    b.Property<int>("OwnerReceiptContractVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerReceiptId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerReceiptSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<long>("ResultingAllocationVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ResultingReservationPseudonym")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId", "LedgerEntryId")
                        .IsUnique();

                    b.HasIndex("ScopeId", "PropertyId", "CompletedAtUtc", "Id");

                    b.ToTable("allocation_anonymisation_tombstones", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_allocation_anonymisation_tombstones_contract", "\"ContractVersion\" = 1");

                            t.HasCheckConstraint("CK_allocation_anonymisation_tombstones_receipt", "\"OwnerReceiptContractVersion\" >= 1 AND char_length(\"OwnerReceiptSha256\") = 64");

                            t.HasCheckConstraint("CK_allocation_anonymisation_tombstones_replay", "(\"LedgerEntryId\" IS NULL AND \"LastReplayedAtUtc\" IS NULL) OR (\"LedgerEntryId\" IS NOT NULL AND \"LastReplayedAtUtc\" IS NOT NULL AND \"LastReplayedAtUtc\" >= \"CompletedAtUtc\")");

                            t.HasCheckConstraint("CK_allocation_anonymisation_tombstones_revision", "\"Revision\" >= 1");

                            t.HasCheckConstraint("CK_allocation_anonymisation_tombstones_version", "\"ResultingAllocationVersion\" >= 1");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Inventory.Domain.Entities.InventoryAllocationUnit", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("AllocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("ScopeId", "AllocationId", "Id");

                    b.HasIndex("ScopeId", "Id", "AllocationId");

                    b.ToTable("allocation_units", "inventory");
                });

            modelBuilder.Entity("BunkFy.Modules.Inventory.Persistence.InventoryAllocationAmendmentDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllocationId")
                        .HasColumnType("uuid");

                    b.Property<long?>("AllocationVersion")
                        .HasColumnType("bigint");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RejectionReason")
                        .HasColumnType("integer");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId", "AllocationId", "DecidedAtUtc");

                    b.ToTable("allocation_amendment_decisions", "inventory");
                });

            modelBuilder.Entity("BunkFy.Modules.Inventory.Persistence.InventoryAllocationOperationLock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllocationId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasAlternateKey("ScopeId", "Id");

                    b.HasIndex("ScopeId", "AllocationId")
                        .IsUnique();

                    b.ToTable("allocation_operation_locks", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_allocation_operation_locks_revision", "\"Revision\" >= 1");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Inventory.Persistence.InventoryBedTopology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("DetailsVersion")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsKnown")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("SourceVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId", "PropertyId", "RoomId", "Label");

                    b.ToTable("bed_topology", "inventory");
                });

            modelBuilder.Entity("BunkFy.Modules.Inventory.Persistence.InventoryProjectionRebuildCheckpoint", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProjectionName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cursor")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("FailedCount")
                        .HasColumnType("bigint");

                    b.Property<long>("ProcessedCount")
                        .HasColumnType("bigint");

                    b.Property<int>("ProjectionVersion")
                        .HasColumnType("integer");

                    b.Property<long>("SkippedCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("WrittenCount")
                        .HasColumnType("bigint");

                    b.HasKey("ScopeId", "ProjectionName", "RunId");

                    b.ToTable("projection_rebuild_checkpoints", "inventory");
                });

            modelBuilder.Entity("BunkFy.Modules.Inventory.Persistence.InventoryPropertyTopology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("DetailsVersion")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsKnown")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("ProjectionOrdinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProjectionOrdinal"));

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("SourceVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectionOrdinal")
                        .IsUnique();

                    b.HasIndex("ScopeId", "Code");

                    b.ToTable("property_topology", "inventory");
                });

            modelBuilder.Entity("BunkFy.Modules.Inventory.Persistence.InventoryRoomTopology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuildingLabel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("DetailsVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("FloorLabel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsKnown")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("SourceVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId", "PropertyId", "Name");

                    b.ToTable("room_topology", "inventory");
                });

            modelBuilder.Entity("BunkFy.Modules.Inventory.Persistence.InventoryUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AvailabilityMutationVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid?>("BedId")
                        .HasColumnType("uuid");

                    b.Property<long>("DetailsVersion")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsKnown")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTopologyActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("SourceVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId", "PropertyId", "RoomId", "Kind");

                    b.ToTable("inventory_units", "inventory");
                });

            modelBuilder.Entity("Gma.Framework.Messaging.Infrastructure.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Handler")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessingStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ScopeId");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id", "Handler");

                    b.HasIndex("Handler", "Status");

                    b.HasIndex("Status", "ProcessedAtUtc");

                    b.ToTable("inbox_messages", "inventory");
                });

            modelBuilder.Entity("Gma.Framework.Messaging.Infrastructure.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ScopeId");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "NextAttemptAtUtc", "LockedUntilUtc", "CreatedAtUtc");

                    b.ToTable("outbox_messages", "inventory");
                });

            modelBuilder.Entity("BunkFy.Modules.Inventory.Domain.Aggregates.ManualInventoryBlock", b =>
                {
                    b.HasOne("BunkFy.Modules.Inventory.Persistence.InventoryUnit", null)
                        .WithMany()
                        .HasForeignKey("ScopeId", "InventoryUnitId")
                        .HasPrincipalKey("ScopeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BunkFy.Modules.Inventory.Domain.DataRights.InventoryAllocationAnonymisationReceipt", b =>
                {
                    b.HasOne("BunkFy.Modules.Inventory.Domain.Aggregates.InventoryAllocation", null)
                        .WithMany()
                        .HasForeignKey("ScopeId", "AllocationId")
                        .HasPrincipalKey("ScopeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BunkFy.Modules.Inventory.Domain.DataRights.InventoryAllocationAnonymisationRestoreReceipt", b =>
                {
                    b.HasOne("BunkFy.Modules.Inventory.Domain.DataRights.InventoryAllocationAnonymisationTombstone", null)
                        .WithMany()
                        .HasForeignKey("ScopeId", "AllocationId")
                        .HasPrincipalKey("ScopeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BunkFy.Modules.Inventory.Domain.Entities.InventoryAllocationUnit", b =>
                {
                    b.HasOne("BunkFy.Modules.Inventory.Domain.Aggregates.InventoryAllocation", null)
                        .WithMany("Units")
                        .HasForeignKey("ScopeId", "AllocationId")
                        .HasPrincipalKey("ScopeId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BunkFy.Modules.Inventory.Domain.Aggregates.InventoryAllocation", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
