// <auto-generated />
using System;
using BunkFy.Modules.DataRights.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BunkFy.Modules.DataRights.Persistence.PostgreSqlMigrations.Migrations
{
    [DbContext(typeof(DataRightsDbContext))]
    [Migration("20260724224218_PrepareAnonymisationExecution")]
    partial class PrepareAnonymisationExecution
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("data-rights")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BunkFy.Modules.DataRights.Domain.Aggregates.DataRightsCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<int>("DecisionReason")
                        .HasColumnType("integer");

                    b.Property<long?>("DecisionRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ExecutionRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ExecutionStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExecutionStartedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequestedOperations")
                        .HasColumnType("integer");

                    b.Property<int>("RequesterRelationship")
                        .HasColumnType("integer");

                    b.Property<int>("RestrictionAction")
                        .HasColumnType("integer")
                        .HasColumnName("RestrictionDirective");

                    b.Property<int>("RoutingStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId", "PropertyId", "Status", "CreatedAtUtc", "Id");

                    b.ToTable("cases", "data-rights", t =>
                        {
                            t.HasCheckConstraint("CK_data_rights_cases_approval_policy_evidence", "(\"Decision\" = 1 AND \"RequestedOperations\" = 16 AND \"ApprovalEvidenceSchemaVersion\" = 1 AND \"ApprovalEvidencePropertyId\" = \"PropertyId\" AND \"ApprovalEvidencePropertyVersion\" > 0 AND \"ApprovalEvidenceOperatingCountryCode\" IS NOT NULL AND char_length(\"ApprovalEvidenceOperatingCountryCode\") = 2 AND \"ApprovalEvidencePolicyId\" IS NOT NULL AND \"ApprovalEvidencePolicyVersion\" > 0 AND \"ApprovalEvidenceRetentionPolicyId\" IS NOT NULL AND \"ApprovalEvidenceRetentionPolicyVersion\" > 0 AND \"ApprovalEvidenceContentSha256\" IS NOT NULL AND char_length(\"ApprovalEvidenceContentSha256\") = 64 AND \"ApprovalEvidencePurposeCode\" = 'data-rights-anonymisation' AND \"ApprovalEvidenceSurface\" = 'erasure' AND \"ApprovalEvidenceSourceProvenance\" = 'authorized-workspace-operator' AND \"ApprovalEvidenceEvaluatedAtUtc\" IS NOT NULL AND \"ApprovalEvidenceRequiresDistinctExecutor\" = TRUE) OR ((\"Decision\" <> 1 OR \"RequestedOperations\" <> 16) AND \"ApprovalEvidenceSchemaVersion\" IS NULL AND \"ApprovalEvidencePropertyId\" IS NULL AND \"ApprovalEvidencePropertyVersion\" IS NULL AND \"ApprovalEvidenceOperatingCountryCode\" IS NULL AND \"ApprovalEvidencePolicyId\" IS NULL AND \"ApprovalEvidencePolicyVersion\" IS NULL AND \"ApprovalEvidenceRetentionPolicyId\" IS NULL AND \"ApprovalEvidenceRetentionPolicyVersion\" IS NULL AND \"ApprovalEvidenceContentSha256\" IS NULL AND \"ApprovalEvidencePurposeCode\" IS NULL AND \"ApprovalEvidenceSurface\" IS NULL AND \"ApprovalEvidenceSourceProvenance\" IS NULL AND \"ApprovalEvidenceEvaluatedAtUtc\" IS NULL AND \"ApprovalEvidenceRequiresDistinctExecutor\" IS NULL)");

                            t.HasCheckConstraint("CK_data_rights_cases_created_by", "length(trim(\"CreatedBy\")) > 0");

                            t.HasCheckConstraint("CK_data_rights_cases_decision", "\"Decision\" BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_data_rights_cases_decision_attribution", "\"DecidedBy\" IS NULL OR (length(trim(\"DecidedBy\")) > 0 AND \"DecidedAtUtc\" >= \"CreatedAtUtc\" AND \"DecidedAtUtc\" <= \"LastChangedAtUtc\")");

                            t.HasCheckConstraint("CK_data_rights_cases_decision_details", "(\"Decision\" = 0 AND \"DecisionRevision\" IS NULL AND \"DecidedBy\" IS NULL AND \"DecidedAtUtc\" IS NULL) OR (\"Decision\" IN (1, 2) AND \"DecisionRevision\" IS NOT NULL AND \"DecisionRevision\" >= 1 AND \"DecisionRevision\" <= \"Version\" AND \"DecidedBy\" IS NOT NULL AND \"DecidedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_data_rights_cases_decision_reason", "\"DecisionReason\" BETWEEN 0 AND 6");

                            t.HasCheckConstraint("CK_data_rights_cases_decision_reason_match", "(\"Decision\" = 0 AND \"DecisionReason\" = 0) OR (\"Decision\" = 1 AND \"DecisionReason\" = 1) OR (\"Decision\" = 2 AND \"DecisionReason\" BETWEEN 2 AND 6)");

                            t.HasCheckConstraint("CK_data_rights_cases_decision_state", "(\"Decision\" = 0 AND \"Status\" IN (1, 2, 3, 4, 11)) OR (\"Decision\" = 1 AND \"Status\" IN (5, 7, 8, 9, 10, 11)) OR (\"Decision\" = 2 AND \"Status\" = 6)");

                            t.HasCheckConstraint("CK_data_rights_cases_execution", "(\"ExecutionRevision\" IS NULL AND \"ExecutionStartedBy\" IS NULL AND \"ExecutionStartedAtUtc\" IS NULL AND \"Status\" IN (1, 2, 3, 4, 5, 6, 11)) OR (\"ExecutionRevision\" IS NOT NULL AND \"ExecutionRevision\" > \"DecisionRevision\" AND \"ExecutionRevision\" <= \"Version\" AND \"ExecutionStartedBy\" IS NOT NULL AND \"ExecutionStartedAtUtc\" IS NOT NULL AND \"Decision\" = 1 AND \"Status\" IN (7, 8, 9, 10, 11))");

                            t.HasCheckConstraint("CK_data_rights_cases_execution_attribution", "\"ExecutionStartedBy\" IS NULL OR (length(trim(\"ExecutionStartedBy\")) > 0 AND \"ExecutionStartedAtUtc\" >= \"DecidedAtUtc\" AND \"ExecutionStartedAtUtc\" <= \"LastChangedAtUtc\")");

                            t.HasCheckConstraint("CK_data_rights_cases_kind", "\"Kind\" IN (1, 2)");

                            t.HasCheckConstraint("CK_data_rights_cases_last_changed_by", "length(trim(\"LastChangedBy\")) > 0");

                            t.HasCheckConstraint("CK_data_rights_cases_operations", "\"RequestedOperations\" BETWEEN 1 AND 31");

                            t.HasCheckConstraint("CK_data_rights_cases_property_scope", "(\"Kind\" = 1 AND \"PropertyId\" IS NOT NULL) OR (\"Kind\" = 2 AND \"PropertyId\" IS NULL)");

                            t.HasCheckConstraint("CK_data_rights_cases_requester", "\"RequesterRelationship\" IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_data_rights_cases_requester_scope", "(\"Kind\" = 1 AND \"RequesterRelationship\" IN (1, 2, 3)) OR (\"Kind\" = 2 AND \"RequesterRelationship\" IN (3, 4))");

                            t.HasCheckConstraint("CK_data_rights_cases_restriction_directive", "((\"RequestedOperations\" & 4) = 0 AND \"RestrictionDirective\" = 0) OR ((\"RequestedOperations\" & 4) = 4 AND \"RestrictionDirective\" BETWEEN 0 AND 2)");

                            t.HasCheckConstraint("CK_data_rights_cases_routing", "\"RoutingStatus\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_data_rights_cases_status", "\"Status\" BETWEEN 1 AND 11");

                            t.HasCheckConstraint("CK_data_rights_cases_timestamps", "\"LastChangedAtUtc\" >= \"CreatedAtUtc\" AND (\"DueAtUtc\" IS NULL OR \"DueAtUtc\" >= \"CreatedAtUtc\")");

                            t.HasCheckConstraint("CK_data_rights_cases_verification", "\"VerificationStatus\" IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_data_rights_cases_version", "\"Version\" >= 1");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.DataRights.Domain.Aggregates.DataRightsExecutionWorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("ApprovalRevision")
                        .HasColumnType("bigint");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("ExecutionRevision")
                        .HasColumnType("bigint");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid");

                    b.Property<int>("Operation")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PolicyContentSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<int>("PolicyEvidenceSchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RetentionPolicyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("RetentionPolicyVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("SelectedRecordVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ScopeId", "PropertyId", "State", "CreatedAtUtc", "Id");

                    b.HasIndex("ScopeId", "CaseId", "ApprovalRevision", "Operation", "OwnerKey", "RecordType", "RecordId")
                        .IsUnique();

                    b.ToTable("execution_work_items", "data-rights", t =>
                        {
                            t.HasCheckConstraint("CK_data_rights_execution_work_items_attempts", "\"AttemptCount\" >= 0");

                            t.HasCheckConstraint("CK_data_rights_execution_work_items_created_by", "length(trim(\"CreatedBy\")) > 0");

                            t.HasCheckConstraint("CK_data_rights_execution_work_items_operation", "\"Operation\" = 16");

                            t.HasCheckConstraint("CK_data_rights_execution_work_items_policy", "\"PolicyEvidenceSchemaVersion\" = 1 AND length(trim(\"PolicyId\")) > 0 AND \"PolicyVersion\" >= 1 AND length(trim(\"RetentionPolicyId\")) > 0 AND \"RetentionPolicyVersion\" >= 1 AND char_length(\"PolicyContentSha256\") = 64");

                            t.HasCheckConstraint("CK_data_rights_execution_work_items_revisions", "\"ApprovalRevision\" >= 1 AND \"ExecutionRevision\" > \"ApprovalRevision\"");

                            t.HasCheckConstraint("CK_data_rights_execution_work_items_state", "\"State\" BETWEEN 1 AND 6");

                            t.HasCheckConstraint("CK_data_rights_execution_work_items_subject", "length(trim(\"OwnerKey\")) > 0 AND length(trim(\"RecordType\")) > 0 AND \"SelectedRecordVersion\" >= 1");

                            t.HasCheckConstraint("CK_data_rights_execution_work_items_version", "\"Version\" >= 1");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.DataRights.Persistence.DataRightsProjectionRebuildCheckpoint", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProjectionName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cursor")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("FailedCount")
                        .HasColumnType("bigint");

                    b.Property<long>("ProcessedCount")
                        .HasColumnType("bigint");

                    b.Property<int>("ProjectionVersion")
                        .HasColumnType("integer");

                    b.Property<long>("SkippedCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("WrittenCount")
                        .HasColumnType("bigint");

                    b.HasKey("ScopeId", "ProjectionName", "RunId");

                    b.ToTable("projection_rebuild_checkpoints", "data-rights");
                });

            modelBuilder.Entity("BunkFy.Modules.DataRights.Persistence.DataRightsPropertyProjection", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsKnown")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("PolicySourceVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int>("ProcessingStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TopologySourceVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("ScopeId", "Id");

                    b.HasIndex("ScopeId", "Status", "Id");

                    b.ToTable("property_projection", "data-rights", t =>
                        {
                            t.HasCheckConstraint("CK_data_rights_property_projection_governance_policy", "(\"ProcessingStatus\" = 1 AND \"OperatingCountryCode\" IS NULL AND \"JurisdictionPolicyId\" IS NULL AND \"JurisdictionPolicyVersion\" IS NULL AND \"DataRegionId\" IS NULL AND \"TransferProfileId\" IS NULL AND \"RetentionPolicyId\" IS NULL AND \"RetentionPolicyVersion\" IS NULL AND \"PolicyContentSha256\" IS NULL AND \"PolicyEffectiveAtUtc\" IS NULL AND \"PolicyExpiresAtUtc\" IS NULL AND \"PolicyActivatedAtUtc\" IS NULL) OR (\"ProcessingStatus\" IN (2, 3) AND \"OperatingCountryCode\" IS NOT NULL AND \"JurisdictionPolicyId\" IS NOT NULL AND \"JurisdictionPolicyVersion\" IS NOT NULL AND \"DataRegionId\" IS NOT NULL AND \"TransferProfileId\" IS NOT NULL AND \"RetentionPolicyId\" IS NOT NULL AND \"RetentionPolicyVersion\" IS NOT NULL AND \"PolicyContentSha256\" IS NOT NULL AND \"PolicyEffectiveAtUtc\" IS NOT NULL AND \"PolicyExpiresAtUtc\" IS NOT NULL AND \"PolicyActivatedAtUtc\" IS NOT NULL AND \"JurisdictionPolicyVersion\" > 0 AND \"RetentionPolicyVersion\" > 0 AND char_length(\"OperatingCountryCode\") = 2 AND char_length(\"PolicyContentSha256\") = 64 AND \"PolicyEffectiveAtUtc\" < \"PolicyExpiresAtUtc\" AND \"PolicyActivatedAtUtc\" >= \"PolicyEffectiveAtUtc\" AND \"PolicyActivatedAtUtc\" < \"PolicyExpiresAtUtc\")");

                            t.HasCheckConstraint("CK_data_rights_property_projection_processing_status", "\"ProcessingStatus\" BETWEEN 1 AND 3");

                            t.HasCheckConstraint("CK_data_rights_property_projection_versions", "\"TopologySourceVersion\" >= 0 AND \"PolicySourceVersion\" >= 0");
                        });
                });

            modelBuilder.Entity("Gma.Framework.Messaging.Infrastructure.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Handler")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessingStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ScopeId");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id", "Handler");

                    b.HasIndex("Handler", "Status");

                    b.HasIndex("Status", "ProcessedAtUtc");

                    b.ToTable("inbox_messages", "data-rights");
                });

            modelBuilder.Entity("Gma.Framework.Messaging.Infrastructure.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ScopeId");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "NextAttemptAtUtc", "LockedUntilUtc", "CreatedAtUtc");

                    b.ToTable("outbox_messages", "data-rights");
                });

            modelBuilder.Entity("BunkFy.Modules.DataRights.Domain.Aggregates.DataRightsCase", b =>
                {
                    b.OwnsMany("BunkFy.Modules.DataRights.Domain.Entities.DataRightsSubjectCoordinate", "SelectedSubjects", b1 =>
                        {
                            b1.Property<Guid>("CaseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("OwnerKey")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("RecordType")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<Guid>("RecordId")
                                .HasColumnType("uuid");

                            b1.Property<long>("RecordVersion")
                                .HasColumnType("bigint");

                            b1.Property<DateTimeOffset>("SelectedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("SelectedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("CaseId", "OwnerKey", "RecordType", "RecordId");

                            b1.ToTable("selected_subjects", "data-rights", t =>
                                {
                                    t.HasCheckConstraint("CK_data_rights_selected_subjects_owner", "length(trim(\"OwnerKey\")) > 0");

                                    t.HasCheckConstraint("CK_data_rights_selected_subjects_record_type", "length(trim(\"RecordType\")) > 0");

                                    t.HasCheckConstraint("CK_data_rights_selected_subjects_record_version", "\"RecordVersion\" >= 1");

                                    t.HasCheckConstraint("CK_data_rights_selected_subjects_selected_by", "length(trim(\"SelectedBy\")) > 0");
                                });

                            b1.WithOwner()
                                .HasForeignKey("CaseId");
                        });

                    b.OwnsOne("BunkFy.Modules.DataRights.Domain.ValueObjects.DataRightsApprovalPolicyEvidence", "ApprovalPolicyEvidence", b1 =>
                        {
                            b1.Property<Guid>("DataRightsCaseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentSha256")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("ApprovalEvidenceContentSha256");

                            b1.Property<DateTimeOffset>("EvaluatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ApprovalEvidenceEvaluatedAtUtc");

                            b1.Property<string>("OperatingCountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("ApprovalEvidenceOperatingCountryCode");

                            b1.Property<string>("PolicyId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("ApprovalEvidencePolicyId");

                            b1.Property<int>("PolicyVersion")
                                .HasColumnType("integer")
                                .HasColumnName("ApprovalEvidencePolicyVersion");

                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uuid")
                                .HasColumnName("ApprovalEvidencePropertyId");

                            b1.Property<long>("PropertyVersion")
                                .HasColumnType("bigint")
                                .HasColumnName("ApprovalEvidencePropertyVersion");

                            b1.Property<string>("PurposeCode")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("ApprovalEvidencePurposeCode");

                            b1.Property<bool>("RequiresDistinctExecutor")
                                .HasColumnType("boolean")
                                .HasColumnName("ApprovalEvidenceRequiresDistinctExecutor");

                            b1.Property<string>("RetentionPolicyId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("ApprovalEvidenceRetentionPolicyId");

                            b1.Property<int>("RetentionPolicyVersion")
                                .HasColumnType("integer")
                                .HasColumnName("ApprovalEvidenceRetentionPolicyVersion");

                            b1.Property<int>("SchemaVersion")
                                .HasColumnType("integer")
                                .HasColumnName("ApprovalEvidenceSchemaVersion");

                            b1.Property<string>("SourceProvenance")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("ApprovalEvidenceSourceProvenance");

                            b1.Property<string>("Surface")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("ApprovalEvidenceSurface");

                            b1.HasKey("DataRightsCaseId");

                            b1.ToTable("cases", "data-rights");

                            b1.WithOwner()
                                .HasForeignKey("DataRightsCaseId");
                        });

                    b.Navigation("ApprovalPolicyEvidence");

                    b.Navigation("SelectedSubjects");
                });

            modelBuilder.Entity("BunkFy.Modules.DataRights.Domain.Aggregates.DataRightsExecutionWorkItem", b =>
                {
                    b.HasOne("BunkFy.Modules.DataRights.Domain.Aggregates.DataRightsCase", null)
                        .WithMany()
                        .HasForeignKey("ScopeId", "CaseId")
                        .HasPrincipalKey("ScopeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BunkFy.Modules.DataRights.Persistence.DataRightsPropertyProjection", b =>
                {
                    b.OwnsOne("BunkFy.Modules.DataRights.Persistence.DataRightsPropertyPolicyBinding", "GovernancePolicy", b1 =>
                        {
                            b1.Property<string>("DataRightsPropertyProjectionScopeId")
                                .HasColumnType("character varying(128)");

                            b1.Property<Guid>("DataRightsPropertyProjectionId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("ActivatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PolicyActivatedAtUtc");

                            b1.Property<string>("ContentSha256")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("PolicyContentSha256");

                            b1.Property<string>("DataRegionId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("DataRegionId");

                            b1.Property<string>("OperatingCountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("OperatingCountryCode");

                            b1.Property<DateTimeOffset>("PolicyEffectiveAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PolicyEffectiveAtUtc");

                            b1.Property<DateTimeOffset>("PolicyExpiresAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PolicyExpiresAtUtc");

                            b1.Property<string>("PolicyId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("JurisdictionPolicyId");

                            b1.Property<int>("PolicyVersion")
                                .HasColumnType("integer")
                                .HasColumnName("JurisdictionPolicyVersion");

                            b1.Property<string>("RetentionPolicyId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("RetentionPolicyId");

                            b1.Property<int>("RetentionPolicyVersion")
                                .HasColumnType("integer")
                                .HasColumnName("RetentionPolicyVersion");

                            b1.Property<string>("TransferProfileId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("TransferProfileId");

                            b1.HasKey("DataRightsPropertyProjectionScopeId", "DataRightsPropertyProjectionId");

                            b1.ToTable("property_projection", "data-rights");

                            b1.WithOwner()
                                .HasForeignKey("DataRightsPropertyProjectionScopeId", "DataRightsPropertyProjectionId");

                            b1.OwnsMany("BunkFy.Modules.DataRights.Persistence.DataRightsPropertyPolicyAcknowledgement", "Acknowledgements", b2 =>
                                {
                                    b2.Property<string>("ScopeId")
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)");

                                    b2.Property<Guid>("PropertyId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("AcknowledgementId")
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)");

                                    b2.Property<int>("AcknowledgementVersion")
                                        .HasColumnType("integer");

                                    b2.HasKey("ScopeId", "PropertyId", "AcknowledgementId", "AcknowledgementVersion");

                                    b2.ToTable("property_policy_acknowledgements", "data-rights");

                                    b2.WithOwner()
                                        .HasForeignKey("ScopeId", "PropertyId");
                                });

                            b1.Navigation("Acknowledgements");
                        });

                    b.Navigation("GovernancePolicy");
                });
#pragma warning restore 612, 618
        }
    }
}
