// <auto-generated />
using System;
using BunkFy.Modules.DataRights.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BunkFy.Modules.DataRights.Persistence.PostgreSqlMigrations.Migrations
{
    [DbContext(typeof(DataRightsDbContext))]
    [Migration("20260723065050_AddSubjectSelection")]
    partial class AddSubjectSelection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("data-rights")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BunkFy.Modules.DataRights.Domain.Aggregates.DataRightsCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequestedOperations")
                        .HasColumnType("integer");

                    b.Property<int>("RequesterRelationship")
                        .HasColumnType("integer");

                    b.Property<int>("RoutingStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("ScopeId", "Id");

                    b.HasIndex("ScopeId", "PropertyId", "Status", "CreatedAtUtc", "Id");

                    b.ToTable("cases", "data-rights", t =>
                        {
                            t.HasCheckConstraint("CK_data_rights_cases_created_by", "length(trim(\"CreatedBy\")) > 0");

                            t.HasCheckConstraint("CK_data_rights_cases_kind", "\"Kind\" IN (1, 2)");

                            t.HasCheckConstraint("CK_data_rights_cases_last_changed_by", "length(trim(\"LastChangedBy\")) > 0");

                            t.HasCheckConstraint("CK_data_rights_cases_operations", "\"RequestedOperations\" BETWEEN 1 AND 31");

                            t.HasCheckConstraint("CK_data_rights_cases_property_scope", "(\"Kind\" = 1 AND \"PropertyId\" IS NOT NULL) OR (\"Kind\" = 2 AND \"PropertyId\" IS NULL)");

                            t.HasCheckConstraint("CK_data_rights_cases_requester", "\"RequesterRelationship\" IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_data_rights_cases_requester_scope", "(\"Kind\" = 1 AND \"RequesterRelationship\" IN (1, 2, 3)) OR (\"Kind\" = 2 AND \"RequesterRelationship\" IN (3, 4))");

                            t.HasCheckConstraint("CK_data_rights_cases_routing", "\"RoutingStatus\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_data_rights_cases_status", "\"Status\" BETWEEN 1 AND 11");

                            t.HasCheckConstraint("CK_data_rights_cases_timestamps", "\"LastChangedAtUtc\" >= \"CreatedAtUtc\" AND (\"DueAtUtc\" IS NULL OR \"DueAtUtc\" >= \"CreatedAtUtc\")");

                            t.HasCheckConstraint("CK_data_rights_cases_verification", "\"VerificationStatus\" IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_data_rights_cases_version", "\"Version\" >= 1");
                        });
                });

            modelBuilder.Entity("Gma.Framework.Messaging.Infrastructure.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Handler")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessingStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ScopeId");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id", "Handler");

                    b.HasIndex("Handler", "Status");

                    b.HasIndex("Status", "ProcessedAtUtc");

                    b.ToTable("inbox_messages", "data-rights");
                });

            modelBuilder.Entity("Gma.Framework.Messaging.Infrastructure.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ScopeId");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "NextAttemptAtUtc", "LockedUntilUtc", "CreatedAtUtc");

                    b.ToTable("outbox_messages", "data-rights");
                });

            modelBuilder.Entity("BunkFy.Modules.DataRights.Domain.Aggregates.DataRightsCase", b =>
                {
                    b.OwnsMany("BunkFy.Modules.DataRights.Domain.Entities.DataRightsSubjectCoordinate", "SelectedSubjects", b1 =>
                        {
                            b1.Property<Guid>("CaseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("OwnerKey")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("RecordType")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<Guid>("RecordId")
                                .HasColumnType("uuid");

                            b1.Property<long>("RecordVersion")
                                .HasColumnType("bigint");

                            b1.Property<DateTimeOffset>("SelectedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("SelectedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("CaseId", "OwnerKey", "RecordType", "RecordId");

                            b1.ToTable("selected_subjects", "data-rights", t =>
                                {
                                    t.HasCheckConstraint("CK_data_rights_selected_subjects_owner", "length(trim(\"OwnerKey\")) > 0");

                                    t.HasCheckConstraint("CK_data_rights_selected_subjects_record_type", "length(trim(\"RecordType\")) > 0");

                                    t.HasCheckConstraint("CK_data_rights_selected_subjects_record_version", "\"RecordVersion\" >= 1");

                                    t.HasCheckConstraint("CK_data_rights_selected_subjects_selected_by", "length(trim(\"SelectedBy\")) > 0");
                                });

                            b1.WithOwner()
                                .HasForeignKey("CaseId");
                        });

                    b.Navigation("SelectedSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
