namespace BunkFy.Modules.Properties.Persistence;

internal sealed class PropertyTimeZoneCatalogEntry
{
    private PropertyTimeZoneCatalogEntry()
    {
    }

    public string CatalogVersion { get; private set; } = string.Empty;

    public string TimeZoneId { get; private set; } = string.Empty;

    public int Ordinal { get; private set; }
}

internal sealed class PropertyTimeZoneCatalogResolution
{
    private PropertyTimeZoneCatalogResolution()
    {
    }

    public string CatalogVersion { get; private set; } = string.Empty;

    public string RequestedTimeZoneId { get; private set; } = string.Empty;

    public string CanonicalTimeZoneId { get; private set; } = string.Empty;

    public int Ordinal { get; private set; }
}

internal static class PropertyTimeZoneCatalogSeed
{
    public const int CatalogVersionMaxLength = 64;
    public const string CurrentCatalogVersion =
        "TZDB: 2026c (mapping: 48.2)";
    public const int CurrentCanonicalIdCount = 340;
    public const string CurrentCanonicalIdsSha256 =
        "6916cb132692f2b2c990b3b8da7ead8819e3ca606acc9b1a093143f80c7c733d";
    public const int CurrentResolutionCount = 597;
    public const string CurrentResolutionsSha256 =
        "b363abb838dfbcafdd96c74343213af659bc714d04bb80e8e8516b62c07f6d02";

    public static IReadOnlyList<string> CanonicalIds { get; } =
    [
        "Africa/Abidjan",
        "Africa/Algiers",
        "Africa/Bissau",
        "Africa/Cairo",
        "Africa/Casablanca",
        "Africa/Ceuta",
        "Africa/El_Aaiun",
        "Africa/Johannesburg",
        "Africa/Juba",
        "Africa/Khartoum",
        "Africa/Lagos",
        "Africa/Maputo",
        "Africa/Monrovia",
        "Africa/Nairobi",
        "Africa/Ndjamena",
        "Africa/Sao_Tome",
        "Africa/Tripoli",
        "Africa/Tunis",
        "Africa/Windhoek",
        "America/Adak",
        "America/Anchorage",
        "America/Araguaina",
        "America/Argentina/Buenos_Aires",
        "America/Argentina/Catamarca",
        "America/Argentina/Cordoba",
        "America/Argentina/Jujuy",
        "America/Argentina/La_Rioja",
        "America/Argentina/Mendoza",
        "America/Argentina/Rio_Gallegos",
        "America/Argentina/Salta",
        "America/Argentina/San_Juan",
        "America/Argentina/San_Luis",
        "America/Argentina/Tucuman",
        "America/Argentina/Ushuaia",
        "America/Asuncion",
        "America/Bahia",
        "America/Bahia_Banderas",
        "America/Barbados",
        "America/Belem",
        "America/Belize",
        "America/Boa_Vista",
        "America/Bogota",
        "America/Boise",
        "America/Cambridge_Bay",
        "America/Campo_Grande",
        "America/Cancun",
        "America/Caracas",
        "America/Cayenne",
        "America/Chicago",
        "America/Chihuahua",
        "America/Ciudad_Juarez",
        "America/Costa_Rica",
        "America/Coyhaique",
        "America/Cuiaba",
        "America/Danmarkshavn",
        "America/Dawson",
        "America/Dawson_Creek",
        "America/Denver",
        "America/Detroit",
        "America/Edmonton",
        "America/Eirunepe",
        "America/El_Salvador",
        "America/Fort_Nelson",
        "America/Fortaleza",
        "America/Glace_Bay",
        "America/Goose_Bay",
        "America/Grand_Turk",
        "America/Guatemala",
        "America/Guayaquil",
        "America/Guyana",
        "America/Halifax",
        "America/Havana",
        "America/Hermosillo",
        "America/Indiana/Indianapolis",
        "America/Indiana/Knox",
        "America/Indiana/Marengo",
        "America/Indiana/Petersburg",
        "America/Indiana/Tell_City",
        "America/Indiana/Vevay",
        "America/Indiana/Vincennes",
        "America/Indiana/Winamac",
        "America/Inuvik",
        "America/Iqaluit",
        "America/Jamaica",
        "America/Juneau",
        "America/Kentucky/Louisville",
        "America/Kentucky/Monticello",
        "America/La_Paz",
        "America/Lima",
        "America/Los_Angeles",
        "America/Maceio",
        "America/Managua",
        "America/Manaus",
        "America/Martinique",
        "America/Matamoros",
        "America/Mazatlan",
        "America/Menominee",
        "America/Merida",
        "America/Metlakatla",
        "America/Mexico_City",
        "America/Miquelon",
        "America/Moncton",
        "America/Monterrey",
        "America/Montevideo",
        "America/New_York",
        "America/Nome",
        "America/Noronha",
        "America/North_Dakota/Beulah",
        "America/North_Dakota/Center",
        "America/North_Dakota/New_Salem",
        "America/Nuuk",
        "America/Ojinaga",
        "America/Panama",
        "America/Paramaribo",
        "America/Phoenix",
        "America/Port-au-Prince",
        "America/Porto_Velho",
        "America/Puerto_Rico",
        "America/Punta_Arenas",
        "America/Rankin_Inlet",
        "America/Recife",
        "America/Regina",
        "America/Resolute",
        "America/Rio_Branco",
        "America/Santarem",
        "America/Santiago",
        "America/Santo_Domingo",
        "America/Sao_Paulo",
        "America/Scoresbysund",
        "America/Sitka",
        "America/St_Johns",
        "America/Swift_Current",
        "America/Tegucigalpa",
        "America/Thule",
        "America/Tijuana",
        "America/Toronto",
        "America/Vancouver",
        "America/Whitehorse",
        "America/Winnipeg",
        "America/Yakutat",
        "Antarctica/Casey",
        "Antarctica/Davis",
        "Antarctica/Macquarie",
        "Antarctica/Mawson",
        "Antarctica/Palmer",
        "Antarctica/Rothera",
        "Antarctica/Troll",
        "Antarctica/Vostok",
        "Asia/Almaty",
        "Asia/Amman",
        "Asia/Anadyr",
        "Asia/Aqtau",
        "Asia/Aqtobe",
        "Asia/Ashgabat",
        "Asia/Atyrau",
        "Asia/Baghdad",
        "Asia/Baku",
        "Asia/Bangkok",
        "Asia/Barnaul",
        "Asia/Beirut",
        "Asia/Bishkek",
        "Asia/Chita",
        "Asia/Colombo",
        "Asia/Damascus",
        "Asia/Dhaka",
        "Asia/Dili",
        "Asia/Dubai",
        "Asia/Dushanbe",
        "Asia/Famagusta",
        "Asia/Gaza",
        "Asia/Hebron",
        "Asia/Ho_Chi_Minh",
        "Asia/Hong_Kong",
        "Asia/Hovd",
        "Asia/Irkutsk",
        "Asia/Jakarta",
        "Asia/Jayapura",
        "Asia/Jerusalem",
        "Asia/Kabul",
        "Asia/Kamchatka",
        "Asia/Karachi",
        "Asia/Kathmandu",
        "Asia/Khandyga",
        "Asia/Kolkata",
        "Asia/Krasnoyarsk",
        "Asia/Kuching",
        "Asia/Macau",
        "Asia/Magadan",
        "Asia/Makassar",
        "Asia/Manila",
        "Asia/Nicosia",
        "Asia/Novokuznetsk",
        "Asia/Novosibirsk",
        "Asia/Omsk",
        "Asia/Oral",
        "Asia/Pontianak",
        "Asia/Pyongyang",
        "Asia/Qatar",
        "Asia/Qostanay",
        "Asia/Qyzylorda",
        "Asia/Riyadh",
        "Asia/Sakhalin",
        "Asia/Samarkand",
        "Asia/Seoul",
        "Asia/Shanghai",
        "Asia/Singapore",
        "Asia/Srednekolymsk",
        "Asia/Taipei",
        "Asia/Tashkent",
        "Asia/Tbilisi",
        "Asia/Tehran",
        "Asia/Thimphu",
        "Asia/Tokyo",
        "Asia/Tomsk",
        "Asia/Ulaanbaatar",
        "Asia/Urumqi",
        "Asia/Ust-Nera",
        "Asia/Vladivostok",
        "Asia/Yakutsk",
        "Asia/Yangon",
        "Asia/Yekaterinburg",
        "Asia/Yerevan",
        "Atlantic/Azores",
        "Atlantic/Bermuda",
        "Atlantic/Canary",
        "Atlantic/Cape_Verde",
        "Atlantic/Faroe",
        "Atlantic/Madeira",
        "Atlantic/South_Georgia",
        "Atlantic/Stanley",
        "Australia/Adelaide",
        "Australia/Brisbane",
        "Australia/Broken_Hill",
        "Australia/Darwin",
        "Australia/Eucla",
        "Australia/Hobart",
        "Australia/Lindeman",
        "Australia/Lord_Howe",
        "Australia/Melbourne",
        "Australia/Perth",
        "Australia/Sydney",
        "Etc/GMT",
        "Etc/GMT+1",
        "Etc/GMT+10",
        "Etc/GMT+11",
        "Etc/GMT+12",
        "Etc/GMT+2",
        "Etc/GMT+3",
        "Etc/GMT+4",
        "Etc/GMT+5",
        "Etc/GMT+6",
        "Etc/GMT+7",
        "Etc/GMT+8",
        "Etc/GMT+9",
        "Etc/GMT-1",
        "Etc/GMT-10",
        "Etc/GMT-11",
        "Etc/GMT-12",
        "Etc/GMT-13",
        "Etc/GMT-14",
        "Etc/GMT-2",
        "Etc/GMT-3",
        "Etc/GMT-4",
        "Etc/GMT-5",
        "Etc/GMT-6",
        "Etc/GMT-7",
        "Etc/GMT-8",
        "Etc/GMT-9",
        "Etc/UTC",
        "Europe/Andorra",
        "Europe/Astrakhan",
        "Europe/Athens",
        "Europe/Belgrade",
        "Europe/Berlin",
        "Europe/Brussels",
        "Europe/Bucharest",
        "Europe/Budapest",
        "Europe/Chisinau",
        "Europe/Dublin",
        "Europe/Gibraltar",
        "Europe/Helsinki",
        "Europe/Istanbul",
        "Europe/Kaliningrad",
        "Europe/Kirov",
        "Europe/Kyiv",
        "Europe/Lisbon",
        "Europe/London",
        "Europe/Madrid",
        "Europe/Malta",
        "Europe/Minsk",
        "Europe/Moscow",
        "Europe/Paris",
        "Europe/Prague",
        "Europe/Riga",
        "Europe/Rome",
        "Europe/Samara",
        "Europe/Saratov",
        "Europe/Simferopol",
        "Europe/Sofia",
        "Europe/Tallinn",
        "Europe/Tirane",
        "Europe/Ulyanovsk",
        "Europe/Vienna",
        "Europe/Vilnius",
        "Europe/Volgograd",
        "Europe/Warsaw",
        "Europe/Zurich",
        "Indian/Chagos",
        "Indian/Maldives",
        "Indian/Mauritius",
        "Pacific/Apia",
        "Pacific/Auckland",
        "Pacific/Bougainville",
        "Pacific/Chatham",
        "Pacific/Easter",
        "Pacific/Efate",
        "Pacific/Fakaofo",
        "Pacific/Fiji",
        "Pacific/Galapagos",
        "Pacific/Gambier",
        "Pacific/Guadalcanal",
        "Pacific/Guam",
        "Pacific/Honolulu",
        "Pacific/Kanton",
        "Pacific/Kiritimati",
        "Pacific/Kosrae",
        "Pacific/Kwajalein",
        "Pacific/Marquesas",
        "Pacific/Nauru",
        "Pacific/Niue",
        "Pacific/Norfolk",
        "Pacific/Noumea",
        "Pacific/Pago_Pago",
        "Pacific/Palau",
        "Pacific/Pitcairn",
        "Pacific/Port_Moresby",
        "Pacific/Rarotonga",
        "Pacific/Tahiti",
        "Pacific/Tarawa",
        "Pacific/Tongatapu",
    ];

    public static IReadOnlyList<PropertyTimeZoneCatalogResolutionVersionEntrySeed>
        Resolutions
    { get; } =
    [
        new("Africa/Abidjan", "Africa/Abidjan", 1),
        new("Africa/Accra", "Africa/Abidjan", 2),
        new("Africa/Addis_Ababa", "Africa/Nairobi", 3),
        new("Africa/Algiers", "Africa/Algiers", 4),
        new("Africa/Asmara", "Africa/Nairobi", 5),
        new("Africa/Asmera", "Africa/Nairobi", 6),
        new("Africa/Bamako", "Africa/Abidjan", 7),
        new("Africa/Bangui", "Africa/Lagos", 8),
        new("Africa/Banjul", "Africa/Abidjan", 9),
        new("Africa/Bissau", "Africa/Bissau", 10),
        new("Africa/Blantyre", "Africa/Maputo", 11),
        new("Africa/Brazzaville", "Africa/Lagos", 12),
        new("Africa/Bujumbura", "Africa/Maputo", 13),
        new("Africa/Cairo", "Africa/Cairo", 14),
        new("Africa/Casablanca", "Africa/Casablanca", 15),
        new("Africa/Ceuta", "Africa/Ceuta", 16),
        new("Africa/Conakry", "Africa/Abidjan", 17),
        new("Africa/Dakar", "Africa/Abidjan", 18),
        new("Africa/Dar_es_Salaam", "Africa/Nairobi", 19),
        new("Africa/Djibouti", "Africa/Nairobi", 20),
        new("Africa/Douala", "Africa/Lagos", 21),
        new("Africa/El_Aaiun", "Africa/El_Aaiun", 22),
        new("Africa/Freetown", "Africa/Abidjan", 23),
        new("Africa/Gaborone", "Africa/Maputo", 24),
        new("Africa/Harare", "Africa/Maputo", 25),
        new("Africa/Johannesburg", "Africa/Johannesburg", 26),
        new("Africa/Juba", "Africa/Juba", 27),
        new("Africa/Kampala", "Africa/Nairobi", 28),
        new("Africa/Khartoum", "Africa/Khartoum", 29),
        new("Africa/Kigali", "Africa/Maputo", 30),
        new("Africa/Kinshasa", "Africa/Lagos", 31),
        new("Africa/Lagos", "Africa/Lagos", 32),
        new("Africa/Libreville", "Africa/Lagos", 33),
        new("Africa/Lome", "Africa/Abidjan", 34),
        new("Africa/Luanda", "Africa/Lagos", 35),
        new("Africa/Lubumbashi", "Africa/Maputo", 36),
        new("Africa/Lusaka", "Africa/Maputo", 37),
        new("Africa/Malabo", "Africa/Lagos", 38),
        new("Africa/Maputo", "Africa/Maputo", 39),
        new("Africa/Maseru", "Africa/Johannesburg", 40),
        new("Africa/Mbabane", "Africa/Johannesburg", 41),
        new("Africa/Mogadishu", "Africa/Nairobi", 42),
        new("Africa/Monrovia", "Africa/Monrovia", 43),
        new("Africa/Nairobi", "Africa/Nairobi", 44),
        new("Africa/Ndjamena", "Africa/Ndjamena", 45),
        new("Africa/Niamey", "Africa/Lagos", 46),
        new("Africa/Nouakchott", "Africa/Abidjan", 47),
        new("Africa/Ouagadougou", "Africa/Abidjan", 48),
        new("Africa/Porto-Novo", "Africa/Lagos", 49),
        new("Africa/Sao_Tome", "Africa/Sao_Tome", 50),
        new("Africa/Timbuktu", "Africa/Abidjan", 51),
        new("Africa/Tripoli", "Africa/Tripoli", 52),
        new("Africa/Tunis", "Africa/Tunis", 53),
        new("Africa/Windhoek", "Africa/Windhoek", 54),
        new("America/Adak", "America/Adak", 55),
        new("America/Anchorage", "America/Anchorage", 56),
        new("America/Anguilla", "America/Puerto_Rico", 57),
        new("America/Antigua", "America/Puerto_Rico", 58),
        new("America/Araguaina", "America/Araguaina", 59),
        new("America/Argentina/Buenos_Aires", "America/Argentina/Buenos_Aires", 60),
        new("America/Argentina/Catamarca", "America/Argentina/Catamarca", 61),
        new("America/Argentina/ComodRivadavia", "America/Argentina/Catamarca", 62),
        new("America/Argentina/Cordoba", "America/Argentina/Cordoba", 63),
        new("America/Argentina/Jujuy", "America/Argentina/Jujuy", 64),
        new("America/Argentina/La_Rioja", "America/Argentina/La_Rioja", 65),
        new("America/Argentina/Mendoza", "America/Argentina/Mendoza", 66),
        new("America/Argentina/Rio_Gallegos", "America/Argentina/Rio_Gallegos", 67),
        new("America/Argentina/Salta", "America/Argentina/Salta", 68),
        new("America/Argentina/San_Juan", "America/Argentina/San_Juan", 69),
        new("America/Argentina/San_Luis", "America/Argentina/San_Luis", 70),
        new("America/Argentina/Tucuman", "America/Argentina/Tucuman", 71),
        new("America/Argentina/Ushuaia", "America/Argentina/Ushuaia", 72),
        new("America/Aruba", "America/Puerto_Rico", 73),
        new("America/Asuncion", "America/Asuncion", 74),
        new("America/Atikokan", "America/Panama", 75),
        new("America/Atka", "America/Adak", 76),
        new("America/Bahia", "America/Bahia", 77),
        new("America/Bahia_Banderas", "America/Bahia_Banderas", 78),
        new("America/Barbados", "America/Barbados", 79),
        new("America/Belem", "America/Belem", 80),
        new("America/Belize", "America/Belize", 81),
        new("America/Blanc-Sablon", "America/Puerto_Rico", 82),
        new("America/Boa_Vista", "America/Boa_Vista", 83),
        new("America/Bogota", "America/Bogota", 84),
        new("America/Boise", "America/Boise", 85),
        new("America/Buenos_Aires", "America/Argentina/Buenos_Aires", 86),
        new("America/Cambridge_Bay", "America/Cambridge_Bay", 87),
        new("America/Campo_Grande", "America/Campo_Grande", 88),
        new("America/Cancun", "America/Cancun", 89),
        new("America/Caracas", "America/Caracas", 90),
        new("America/Catamarca", "America/Argentina/Catamarca", 91),
        new("America/Cayenne", "America/Cayenne", 92),
        new("America/Cayman", "America/Panama", 93),
        new("America/Chicago", "America/Chicago", 94),
        new("America/Chihuahua", "America/Chihuahua", 95),
        new("America/Ciudad_Juarez", "America/Ciudad_Juarez", 96),
        new("America/Coral_Harbour", "America/Panama", 97),
        new("America/Cordoba", "America/Argentina/Cordoba", 98),
        new("America/Costa_Rica", "America/Costa_Rica", 99),
        new("America/Coyhaique", "America/Coyhaique", 100),
        new("America/Creston", "America/Phoenix", 101),
        new("America/Cuiaba", "America/Cuiaba", 102),
        new("America/Curacao", "America/Puerto_Rico", 103),
        new("America/Danmarkshavn", "America/Danmarkshavn", 104),
        new("America/Dawson", "America/Dawson", 105),
        new("America/Dawson_Creek", "America/Dawson_Creek", 106),
        new("America/Denver", "America/Denver", 107),
        new("America/Detroit", "America/Detroit", 108),
        new("America/Dominica", "America/Puerto_Rico", 109),
        new("America/Edmonton", "America/Edmonton", 110),
        new("America/Eirunepe", "America/Eirunepe", 111),
        new("America/El_Salvador", "America/El_Salvador", 112),
        new("America/Ensenada", "America/Tijuana", 113),
        new("America/Fort_Nelson", "America/Fort_Nelson", 114),
        new("America/Fort_Wayne", "America/Indiana/Indianapolis", 115),
        new("America/Fortaleza", "America/Fortaleza", 116),
        new("America/Glace_Bay", "America/Glace_Bay", 117),
        new("America/Godthab", "America/Nuuk", 118),
        new("America/Goose_Bay", "America/Goose_Bay", 119),
        new("America/Grand_Turk", "America/Grand_Turk", 120),
        new("America/Grenada", "America/Puerto_Rico", 121),
        new("America/Guadeloupe", "America/Puerto_Rico", 122),
        new("America/Guatemala", "America/Guatemala", 123),
        new("America/Guayaquil", "America/Guayaquil", 124),
        new("America/Guyana", "America/Guyana", 125),
        new("America/Halifax", "America/Halifax", 126),
        new("America/Havana", "America/Havana", 127),
        new("America/Hermosillo", "America/Hermosillo", 128),
        new("America/Indiana/Indianapolis", "America/Indiana/Indianapolis", 129),
        new("America/Indiana/Knox", "America/Indiana/Knox", 130),
        new("America/Indiana/Marengo", "America/Indiana/Marengo", 131),
        new("America/Indiana/Petersburg", "America/Indiana/Petersburg", 132),
        new("America/Indiana/Tell_City", "America/Indiana/Tell_City", 133),
        new("America/Indiana/Vevay", "America/Indiana/Vevay", 134),
        new("America/Indiana/Vincennes", "America/Indiana/Vincennes", 135),
        new("America/Indiana/Winamac", "America/Indiana/Winamac", 136),
        new("America/Indianapolis", "America/Indiana/Indianapolis", 137),
        new("America/Inuvik", "America/Inuvik", 138),
        new("America/Iqaluit", "America/Iqaluit", 139),
        new("America/Jamaica", "America/Jamaica", 140),
        new("America/Jujuy", "America/Argentina/Jujuy", 141),
        new("America/Juneau", "America/Juneau", 142),
        new("America/Kentucky/Louisville", "America/Kentucky/Louisville", 143),
        new("America/Kentucky/Monticello", "America/Kentucky/Monticello", 144),
        new("America/Knox_IN", "America/Indiana/Knox", 145),
        new("America/Kralendijk", "America/Puerto_Rico", 146),
        new("America/La_Paz", "America/La_Paz", 147),
        new("America/Lima", "America/Lima", 148),
        new("America/Los_Angeles", "America/Los_Angeles", 149),
        new("America/Louisville", "America/Kentucky/Louisville", 150),
        new("America/Lower_Princes", "America/Puerto_Rico", 151),
        new("America/Maceio", "America/Maceio", 152),
        new("America/Managua", "America/Managua", 153),
        new("America/Manaus", "America/Manaus", 154),
        new("America/Marigot", "America/Puerto_Rico", 155),
        new("America/Martinique", "America/Martinique", 156),
        new("America/Matamoros", "America/Matamoros", 157),
        new("America/Mazatlan", "America/Mazatlan", 158),
        new("America/Mendoza", "America/Argentina/Mendoza", 159),
        new("America/Menominee", "America/Menominee", 160),
        new("America/Merida", "America/Merida", 161),
        new("America/Metlakatla", "America/Metlakatla", 162),
        new("America/Mexico_City", "America/Mexico_City", 163),
        new("America/Miquelon", "America/Miquelon", 164),
        new("America/Moncton", "America/Moncton", 165),
        new("America/Monterrey", "America/Monterrey", 166),
        new("America/Montevideo", "America/Montevideo", 167),
        new("America/Montreal", "America/Toronto", 168),
        new("America/Montserrat", "America/Puerto_Rico", 169),
        new("America/Nassau", "America/Toronto", 170),
        new("America/New_York", "America/New_York", 171),
        new("America/Nipigon", "America/Toronto", 172),
        new("America/Nome", "America/Nome", 173),
        new("America/Noronha", "America/Noronha", 174),
        new("America/North_Dakota/Beulah", "America/North_Dakota/Beulah", 175),
        new("America/North_Dakota/Center", "America/North_Dakota/Center", 176),
        new("America/North_Dakota/New_Salem", "America/North_Dakota/New_Salem", 177),
        new("America/Nuuk", "America/Nuuk", 178),
        new("America/Ojinaga", "America/Ojinaga", 179),
        new("America/Panama", "America/Panama", 180),
        new("America/Pangnirtung", "America/Iqaluit", 181),
        new("America/Paramaribo", "America/Paramaribo", 182),
        new("America/Phoenix", "America/Phoenix", 183),
        new("America/Port-au-Prince", "America/Port-au-Prince", 184),
        new("America/Port_of_Spain", "America/Puerto_Rico", 185),
        new("America/Porto_Acre", "America/Rio_Branco", 186),
        new("America/Porto_Velho", "America/Porto_Velho", 187),
        new("America/Puerto_Rico", "America/Puerto_Rico", 188),
        new("America/Punta_Arenas", "America/Punta_Arenas", 189),
        new("America/Rainy_River", "America/Winnipeg", 190),
        new("America/Rankin_Inlet", "America/Rankin_Inlet", 191),
        new("America/Recife", "America/Recife", 192),
        new("America/Regina", "America/Regina", 193),
        new("America/Resolute", "America/Resolute", 194),
        new("America/Rio_Branco", "America/Rio_Branco", 195),
        new("America/Rosario", "America/Argentina/Cordoba", 196),
        new("America/Santa_Isabel", "America/Tijuana", 197),
        new("America/Santarem", "America/Santarem", 198),
        new("America/Santiago", "America/Santiago", 199),
        new("America/Santo_Domingo", "America/Santo_Domingo", 200),
        new("America/Sao_Paulo", "America/Sao_Paulo", 201),
        new("America/Scoresbysund", "America/Scoresbysund", 202),
        new("America/Shiprock", "America/Denver", 203),
        new("America/Sitka", "America/Sitka", 204),
        new("America/St_Barthelemy", "America/Puerto_Rico", 205),
        new("America/St_Johns", "America/St_Johns", 206),
        new("America/St_Kitts", "America/Puerto_Rico", 207),
        new("America/St_Lucia", "America/Puerto_Rico", 208),
        new("America/St_Thomas", "America/Puerto_Rico", 209),
        new("America/St_Vincent", "America/Puerto_Rico", 210),
        new("America/Swift_Current", "America/Swift_Current", 211),
        new("America/Tegucigalpa", "America/Tegucigalpa", 212),
        new("America/Thule", "America/Thule", 213),
        new("America/Thunder_Bay", "America/Toronto", 214),
        new("America/Tijuana", "America/Tijuana", 215),
        new("America/Toronto", "America/Toronto", 216),
        new("America/Tortola", "America/Puerto_Rico", 217),
        new("America/Vancouver", "America/Vancouver", 218),
        new("America/Virgin", "America/Puerto_Rico", 219),
        new("America/Whitehorse", "America/Whitehorse", 220),
        new("America/Winnipeg", "America/Winnipeg", 221),
        new("America/Yakutat", "America/Yakutat", 222),
        new("America/Yellowknife", "America/Edmonton", 223),
        new("Antarctica/Casey", "Antarctica/Casey", 224),
        new("Antarctica/Davis", "Antarctica/Davis", 225),
        new("Antarctica/DumontDUrville", "Pacific/Port_Moresby", 226),
        new("Antarctica/Macquarie", "Antarctica/Macquarie", 227),
        new("Antarctica/Mawson", "Antarctica/Mawson", 228),
        new("Antarctica/McMurdo", "Pacific/Auckland", 229),
        new("Antarctica/Palmer", "Antarctica/Palmer", 230),
        new("Antarctica/Rothera", "Antarctica/Rothera", 231),
        new("Antarctica/South_Pole", "Pacific/Auckland", 232),
        new("Antarctica/Syowa", "Asia/Riyadh", 233),
        new("Antarctica/Troll", "Antarctica/Troll", 234),
        new("Antarctica/Vostok", "Antarctica/Vostok", 235),
        new("Arctic/Longyearbyen", "Europe/Berlin", 236),
        new("Asia/Aden", "Asia/Riyadh", 237),
        new("Asia/Almaty", "Asia/Almaty", 238),
        new("Asia/Amman", "Asia/Amman", 239),
        new("Asia/Anadyr", "Asia/Anadyr", 240),
        new("Asia/Aqtau", "Asia/Aqtau", 241),
        new("Asia/Aqtobe", "Asia/Aqtobe", 242),
        new("Asia/Ashgabat", "Asia/Ashgabat", 243),
        new("Asia/Ashkhabad", "Asia/Ashgabat", 244),
        new("Asia/Atyrau", "Asia/Atyrau", 245),
        new("Asia/Baghdad", "Asia/Baghdad", 246),
        new("Asia/Bahrain", "Asia/Qatar", 247),
        new("Asia/Baku", "Asia/Baku", 248),
        new("Asia/Bangkok", "Asia/Bangkok", 249),
        new("Asia/Barnaul", "Asia/Barnaul", 250),
        new("Asia/Beirut", "Asia/Beirut", 251),
        new("Asia/Bishkek", "Asia/Bishkek", 252),
        new("Asia/Brunei", "Asia/Kuching", 253),
        new("Asia/Calcutta", "Asia/Kolkata", 254),
        new("Asia/Chita", "Asia/Chita", 255),
        new("Asia/Choibalsan", "Asia/Ulaanbaatar", 256),
        new("Asia/Chongqing", "Asia/Shanghai", 257),
        new("Asia/Chungking", "Asia/Shanghai", 258),
        new("Asia/Colombo", "Asia/Colombo", 259),
        new("Asia/Dacca", "Asia/Dhaka", 260),
        new("Asia/Damascus", "Asia/Damascus", 261),
        new("Asia/Dhaka", "Asia/Dhaka", 262),
        new("Asia/Dili", "Asia/Dili", 263),
        new("Asia/Dubai", "Asia/Dubai", 264),
        new("Asia/Dushanbe", "Asia/Dushanbe", 265),
        new("Asia/Famagusta", "Asia/Famagusta", 266),
        new("Asia/Gaza", "Asia/Gaza", 267),
        new("Asia/Harbin", "Asia/Shanghai", 268),
        new("Asia/Hebron", "Asia/Hebron", 269),
        new("Asia/Ho_Chi_Minh", "Asia/Ho_Chi_Minh", 270),
        new("Asia/Hong_Kong", "Asia/Hong_Kong", 271),
        new("Asia/Hovd", "Asia/Hovd", 272),
        new("Asia/Irkutsk", "Asia/Irkutsk", 273),
        new("Asia/Istanbul", "Europe/Istanbul", 274),
        new("Asia/Jakarta", "Asia/Jakarta", 275),
        new("Asia/Jayapura", "Asia/Jayapura", 276),
        new("Asia/Jerusalem", "Asia/Jerusalem", 277),
        new("Asia/Kabul", "Asia/Kabul", 278),
        new("Asia/Kamchatka", "Asia/Kamchatka", 279),
        new("Asia/Karachi", "Asia/Karachi", 280),
        new("Asia/Kashgar", "Asia/Urumqi", 281),
        new("Asia/Kathmandu", "Asia/Kathmandu", 282),
        new("Asia/Katmandu", "Asia/Kathmandu", 283),
        new("Asia/Khandyga", "Asia/Khandyga", 284),
        new("Asia/Kolkata", "Asia/Kolkata", 285),
        new("Asia/Krasnoyarsk", "Asia/Krasnoyarsk", 286),
        new("Asia/Kuala_Lumpur", "Asia/Singapore", 287),
        new("Asia/Kuching", "Asia/Kuching", 288),
        new("Asia/Kuwait", "Asia/Riyadh", 289),
        new("Asia/Macao", "Asia/Macau", 290),
        new("Asia/Macau", "Asia/Macau", 291),
        new("Asia/Magadan", "Asia/Magadan", 292),
        new("Asia/Makassar", "Asia/Makassar", 293),
        new("Asia/Manila", "Asia/Manila", 294),
        new("Asia/Muscat", "Asia/Dubai", 295),
        new("Asia/Nicosia", "Asia/Nicosia", 296),
        new("Asia/Novokuznetsk", "Asia/Novokuznetsk", 297),
        new("Asia/Novosibirsk", "Asia/Novosibirsk", 298),
        new("Asia/Omsk", "Asia/Omsk", 299),
        new("Asia/Oral", "Asia/Oral", 300),
        new("Asia/Phnom_Penh", "Asia/Bangkok", 301),
        new("Asia/Pontianak", "Asia/Pontianak", 302),
        new("Asia/Pyongyang", "Asia/Pyongyang", 303),
        new("Asia/Qatar", "Asia/Qatar", 304),
        new("Asia/Qostanay", "Asia/Qostanay", 305),
        new("Asia/Qyzylorda", "Asia/Qyzylorda", 306),
        new("Asia/Rangoon", "Asia/Yangon", 307),
        new("Asia/Riyadh", "Asia/Riyadh", 308),
        new("Asia/Saigon", "Asia/Ho_Chi_Minh", 309),
        new("Asia/Sakhalin", "Asia/Sakhalin", 310),
        new("Asia/Samarkand", "Asia/Samarkand", 311),
        new("Asia/Seoul", "Asia/Seoul", 312),
        new("Asia/Shanghai", "Asia/Shanghai", 313),
        new("Asia/Singapore", "Asia/Singapore", 314),
        new("Asia/Srednekolymsk", "Asia/Srednekolymsk", 315),
        new("Asia/Taipei", "Asia/Taipei", 316),
        new("Asia/Tashkent", "Asia/Tashkent", 317),
        new("Asia/Tbilisi", "Asia/Tbilisi", 318),
        new("Asia/Tehran", "Asia/Tehran", 319),
        new("Asia/Tel_Aviv", "Asia/Jerusalem", 320),
        new("Asia/Thimbu", "Asia/Thimphu", 321),
        new("Asia/Thimphu", "Asia/Thimphu", 322),
        new("Asia/Tokyo", "Asia/Tokyo", 323),
        new("Asia/Tomsk", "Asia/Tomsk", 324),
        new("Asia/Ujung_Pandang", "Asia/Makassar", 325),
        new("Asia/Ulaanbaatar", "Asia/Ulaanbaatar", 326),
        new("Asia/Ulan_Bator", "Asia/Ulaanbaatar", 327),
        new("Asia/Urumqi", "Asia/Urumqi", 328),
        new("Asia/Ust-Nera", "Asia/Ust-Nera", 329),
        new("Asia/Vientiane", "Asia/Bangkok", 330),
        new("Asia/Vladivostok", "Asia/Vladivostok", 331),
        new("Asia/Yakutsk", "Asia/Yakutsk", 332),
        new("Asia/Yangon", "Asia/Yangon", 333),
        new("Asia/Yekaterinburg", "Asia/Yekaterinburg", 334),
        new("Asia/Yerevan", "Asia/Yerevan", 335),
        new("Atlantic/Azores", "Atlantic/Azores", 336),
        new("Atlantic/Bermuda", "Atlantic/Bermuda", 337),
        new("Atlantic/Canary", "Atlantic/Canary", 338),
        new("Atlantic/Cape_Verde", "Atlantic/Cape_Verde", 339),
        new("Atlantic/Faeroe", "Atlantic/Faroe", 340),
        new("Atlantic/Faroe", "Atlantic/Faroe", 341),
        new("Atlantic/Jan_Mayen", "Europe/Berlin", 342),
        new("Atlantic/Madeira", "Atlantic/Madeira", 343),
        new("Atlantic/Reykjavik", "Africa/Abidjan", 344),
        new("Atlantic/South_Georgia", "Atlantic/South_Georgia", 345),
        new("Atlantic/St_Helena", "Africa/Abidjan", 346),
        new("Atlantic/Stanley", "Atlantic/Stanley", 347),
        new("Australia/ACT", "Australia/Sydney", 348),
        new("Australia/Adelaide", "Australia/Adelaide", 349),
        new("Australia/Brisbane", "Australia/Brisbane", 350),
        new("Australia/Broken_Hill", "Australia/Broken_Hill", 351),
        new("Australia/Canberra", "Australia/Sydney", 352),
        new("Australia/Currie", "Australia/Hobart", 353),
        new("Australia/Darwin", "Australia/Darwin", 354),
        new("Australia/Eucla", "Australia/Eucla", 355),
        new("Australia/Hobart", "Australia/Hobart", 356),
        new("Australia/LHI", "Australia/Lord_Howe", 357),
        new("Australia/Lindeman", "Australia/Lindeman", 358),
        new("Australia/Lord_Howe", "Australia/Lord_Howe", 359),
        new("Australia/Melbourne", "Australia/Melbourne", 360),
        new("Australia/NSW", "Australia/Sydney", 361),
        new("Australia/North", "Australia/Darwin", 362),
        new("Australia/Perth", "Australia/Perth", 363),
        new("Australia/Queensland", "Australia/Brisbane", 364),
        new("Australia/South", "Australia/Adelaide", 365),
        new("Australia/Sydney", "Australia/Sydney", 366),
        new("Australia/Tasmania", "Australia/Hobart", 367),
        new("Australia/Victoria", "Australia/Melbourne", 368),
        new("Australia/West", "Australia/Perth", 369),
        new("Australia/Yancowinna", "Australia/Broken_Hill", 370),
        new("Brazil/Acre", "America/Rio_Branco", 371),
        new("Brazil/DeNoronha", "America/Noronha", 372),
        new("Brazil/East", "America/Sao_Paulo", 373),
        new("Brazil/West", "America/Manaus", 374),
        new("CET", "Europe/Brussels", 375),
        new("CST6CDT", "America/Chicago", 376),
        new("Canada/Atlantic", "America/Halifax", 377),
        new("Canada/Central", "America/Winnipeg", 378),
        new("Canada/Eastern", "America/Toronto", 379),
        new("Canada/Mountain", "America/Edmonton", 380),
        new("Canada/Newfoundland", "America/St_Johns", 381),
        new("Canada/Pacific", "America/Vancouver", 382),
        new("Canada/Saskatchewan", "America/Regina", 383),
        new("Canada/Yukon", "America/Whitehorse", 384),
        new("Chile/Continental", "America/Santiago", 385),
        new("Chile/EasterIsland", "Pacific/Easter", 386),
        new("Cuba", "America/Havana", 387),
        new("EET", "Europe/Athens", 388),
        new("EST", "America/Panama", 389),
        new("EST5EDT", "America/New_York", 390),
        new("Egypt", "Africa/Cairo", 391),
        new("Eire", "Europe/Dublin", 392),
        new("Etc/GMT", "Etc/GMT", 393),
        new("Etc/GMT+0", "Etc/GMT", 394),
        new("Etc/GMT+1", "Etc/GMT+1", 395),
        new("Etc/GMT+10", "Etc/GMT+10", 396),
        new("Etc/GMT+11", "Etc/GMT+11", 397),
        new("Etc/GMT+12", "Etc/GMT+12", 398),
        new("Etc/GMT+2", "Etc/GMT+2", 399),
        new("Etc/GMT+3", "Etc/GMT+3", 400),
        new("Etc/GMT+4", "Etc/GMT+4", 401),
        new("Etc/GMT+5", "Etc/GMT+5", 402),
        new("Etc/GMT+6", "Etc/GMT+6", 403),
        new("Etc/GMT+7", "Etc/GMT+7", 404),
        new("Etc/GMT+8", "Etc/GMT+8", 405),
        new("Etc/GMT+9", "Etc/GMT+9", 406),
        new("Etc/GMT-0", "Etc/GMT", 407),
        new("Etc/GMT-1", "Etc/GMT-1", 408),
        new("Etc/GMT-10", "Etc/GMT-10", 409),
        new("Etc/GMT-11", "Etc/GMT-11", 410),
        new("Etc/GMT-12", "Etc/GMT-12", 411),
        new("Etc/GMT-13", "Etc/GMT-13", 412),
        new("Etc/GMT-14", "Etc/GMT-14", 413),
        new("Etc/GMT-2", "Etc/GMT-2", 414),
        new("Etc/GMT-3", "Etc/GMT-3", 415),
        new("Etc/GMT-4", "Etc/GMT-4", 416),
        new("Etc/GMT-5", "Etc/GMT-5", 417),
        new("Etc/GMT-6", "Etc/GMT-6", 418),
        new("Etc/GMT-7", "Etc/GMT-7", 419),
        new("Etc/GMT-8", "Etc/GMT-8", 420),
        new("Etc/GMT-9", "Etc/GMT-9", 421),
        new("Etc/GMT0", "Etc/GMT", 422),
        new("Etc/Greenwich", "Etc/GMT", 423),
        new("Etc/UCT", "Etc/UTC", 424),
        new("Etc/UTC", "Etc/UTC", 425),
        new("Etc/Universal", "Etc/UTC", 426),
        new("Etc/Zulu", "Etc/UTC", 427),
        new("Europe/Amsterdam", "Europe/Brussels", 428),
        new("Europe/Andorra", "Europe/Andorra", 429),
        new("Europe/Astrakhan", "Europe/Astrakhan", 430),
        new("Europe/Athens", "Europe/Athens", 431),
        new("Europe/Belfast", "Europe/London", 432),
        new("Europe/Belgrade", "Europe/Belgrade", 433),
        new("Europe/Berlin", "Europe/Berlin", 434),
        new("Europe/Bratislava", "Europe/Prague", 435),
        new("Europe/Brussels", "Europe/Brussels", 436),
        new("Europe/Bucharest", "Europe/Bucharest", 437),
        new("Europe/Budapest", "Europe/Budapest", 438),
        new("Europe/Busingen", "Europe/Zurich", 439),
        new("Europe/Chisinau", "Europe/Chisinau", 440),
        new("Europe/Copenhagen", "Europe/Berlin", 441),
        new("Europe/Dublin", "Europe/Dublin", 442),
        new("Europe/Gibraltar", "Europe/Gibraltar", 443),
        new("Europe/Guernsey", "Europe/London", 444),
        new("Europe/Helsinki", "Europe/Helsinki", 445),
        new("Europe/Isle_of_Man", "Europe/London", 446),
        new("Europe/Istanbul", "Europe/Istanbul", 447),
        new("Europe/Jersey", "Europe/London", 448),
        new("Europe/Kaliningrad", "Europe/Kaliningrad", 449),
        new("Europe/Kiev", "Europe/Kyiv", 450),
        new("Europe/Kirov", "Europe/Kirov", 451),
        new("Europe/Kyiv", "Europe/Kyiv", 452),
        new("Europe/Lisbon", "Europe/Lisbon", 453),
        new("Europe/Ljubljana", "Europe/Belgrade", 454),
        new("Europe/London", "Europe/London", 455),
        new("Europe/Luxembourg", "Europe/Brussels", 456),
        new("Europe/Madrid", "Europe/Madrid", 457),
        new("Europe/Malta", "Europe/Malta", 458),
        new("Europe/Mariehamn", "Europe/Helsinki", 459),
        new("Europe/Minsk", "Europe/Minsk", 460),
        new("Europe/Monaco", "Europe/Paris", 461),
        new("Europe/Moscow", "Europe/Moscow", 462),
        new("Europe/Nicosia", "Asia/Nicosia", 463),
        new("Europe/Oslo", "Europe/Berlin", 464),
        new("Europe/Paris", "Europe/Paris", 465),
        new("Europe/Podgorica", "Europe/Belgrade", 466),
        new("Europe/Prague", "Europe/Prague", 467),
        new("Europe/Riga", "Europe/Riga", 468),
        new("Europe/Rome", "Europe/Rome", 469),
        new("Europe/Samara", "Europe/Samara", 470),
        new("Europe/San_Marino", "Europe/Rome", 471),
        new("Europe/Sarajevo", "Europe/Belgrade", 472),
        new("Europe/Saratov", "Europe/Saratov", 473),
        new("Europe/Simferopol", "Europe/Simferopol", 474),
        new("Europe/Skopje", "Europe/Belgrade", 475),
        new("Europe/Sofia", "Europe/Sofia", 476),
        new("Europe/Stockholm", "Europe/Berlin", 477),
        new("Europe/Tallinn", "Europe/Tallinn", 478),
        new("Europe/Tirane", "Europe/Tirane", 479),
        new("Europe/Tiraspol", "Europe/Chisinau", 480),
        new("Europe/Ulyanovsk", "Europe/Ulyanovsk", 481),
        new("Europe/Uzhgorod", "Europe/Kyiv", 482),
        new("Europe/Vaduz", "Europe/Zurich", 483),
        new("Europe/Vatican", "Europe/Rome", 484),
        new("Europe/Vienna", "Europe/Vienna", 485),
        new("Europe/Vilnius", "Europe/Vilnius", 486),
        new("Europe/Volgograd", "Europe/Volgograd", 487),
        new("Europe/Warsaw", "Europe/Warsaw", 488),
        new("Europe/Zagreb", "Europe/Belgrade", 489),
        new("Europe/Zaporozhye", "Europe/Kyiv", 490),
        new("Europe/Zurich", "Europe/Zurich", 491),
        new("GB", "Europe/London", 492),
        new("GB-Eire", "Europe/London", 493),
        new("GMT", "Etc/GMT", 494),
        new("GMT+0", "Etc/GMT", 495),
        new("GMT-0", "Etc/GMT", 496),
        new("GMT0", "Etc/GMT", 497),
        new("Greenwich", "Etc/GMT", 498),
        new("HST", "Pacific/Honolulu", 499),
        new("Hongkong", "Asia/Hong_Kong", 500),
        new("Iceland", "Africa/Abidjan", 501),
        new("Indian/Antananarivo", "Africa/Nairobi", 502),
        new("Indian/Chagos", "Indian/Chagos", 503),
        new("Indian/Christmas", "Asia/Bangkok", 504),
        new("Indian/Cocos", "Asia/Yangon", 505),
        new("Indian/Comoro", "Africa/Nairobi", 506),
        new("Indian/Kerguelen", "Indian/Maldives", 507),
        new("Indian/Mahe", "Asia/Dubai", 508),
        new("Indian/Maldives", "Indian/Maldives", 509),
        new("Indian/Mauritius", "Indian/Mauritius", 510),
        new("Indian/Mayotte", "Africa/Nairobi", 511),
        new("Indian/Reunion", "Asia/Dubai", 512),
        new("Iran", "Asia/Tehran", 513),
        new("Israel", "Asia/Jerusalem", 514),
        new("Jamaica", "America/Jamaica", 515),
        new("Japan", "Asia/Tokyo", 516),
        new("Kwajalein", "Pacific/Kwajalein", 517),
        new("Libya", "Africa/Tripoli", 518),
        new("MET", "Europe/Brussels", 519),
        new("MST", "America/Phoenix", 520),
        new("MST7MDT", "America/Denver", 521),
        new("Mexico/BajaNorte", "America/Tijuana", 522),
        new("Mexico/BajaSur", "America/Mazatlan", 523),
        new("Mexico/General", "America/Mexico_City", 524),
        new("NZ", "Pacific/Auckland", 525),
        new("NZ-CHAT", "Pacific/Chatham", 526),
        new("Navajo", "America/Denver", 527),
        new("PRC", "Asia/Shanghai", 528),
        new("PST8PDT", "America/Los_Angeles", 529),
        new("Pacific/Apia", "Pacific/Apia", 530),
        new("Pacific/Auckland", "Pacific/Auckland", 531),
        new("Pacific/Bougainville", "Pacific/Bougainville", 532),
        new("Pacific/Chatham", "Pacific/Chatham", 533),
        new("Pacific/Chuuk", "Pacific/Port_Moresby", 534),
        new("Pacific/Easter", "Pacific/Easter", 535),
        new("Pacific/Efate", "Pacific/Efate", 536),
        new("Pacific/Enderbury", "Pacific/Kanton", 537),
        new("Pacific/Fakaofo", "Pacific/Fakaofo", 538),
        new("Pacific/Fiji", "Pacific/Fiji", 539),
        new("Pacific/Funafuti", "Pacific/Tarawa", 540),
        new("Pacific/Galapagos", "Pacific/Galapagos", 541),
        new("Pacific/Gambier", "Pacific/Gambier", 542),
        new("Pacific/Guadalcanal", "Pacific/Guadalcanal", 543),
        new("Pacific/Guam", "Pacific/Guam", 544),
        new("Pacific/Honolulu", "Pacific/Honolulu", 545),
        new("Pacific/Johnston", "Pacific/Honolulu", 546),
        new("Pacific/Kanton", "Pacific/Kanton", 547),
        new("Pacific/Kiritimati", "Pacific/Kiritimati", 548),
        new("Pacific/Kosrae", "Pacific/Kosrae", 549),
        new("Pacific/Kwajalein", "Pacific/Kwajalein", 550),
        new("Pacific/Majuro", "Pacific/Tarawa", 551),
        new("Pacific/Marquesas", "Pacific/Marquesas", 552),
        new("Pacific/Midway", "Pacific/Pago_Pago", 553),
        new("Pacific/Nauru", "Pacific/Nauru", 554),
        new("Pacific/Niue", "Pacific/Niue", 555),
        new("Pacific/Norfolk", "Pacific/Norfolk", 556),
        new("Pacific/Noumea", "Pacific/Noumea", 557),
        new("Pacific/Pago_Pago", "Pacific/Pago_Pago", 558),
        new("Pacific/Palau", "Pacific/Palau", 559),
        new("Pacific/Pitcairn", "Pacific/Pitcairn", 560),
        new("Pacific/Pohnpei", "Pacific/Guadalcanal", 561),
        new("Pacific/Ponape", "Pacific/Guadalcanal", 562),
        new("Pacific/Port_Moresby", "Pacific/Port_Moresby", 563),
        new("Pacific/Rarotonga", "Pacific/Rarotonga", 564),
        new("Pacific/Saipan", "Pacific/Guam", 565),
        new("Pacific/Samoa", "Pacific/Pago_Pago", 566),
        new("Pacific/Tahiti", "Pacific/Tahiti", 567),
        new("Pacific/Tarawa", "Pacific/Tarawa", 568),
        new("Pacific/Tongatapu", "Pacific/Tongatapu", 569),
        new("Pacific/Truk", "Pacific/Port_Moresby", 570),
        new("Pacific/Wake", "Pacific/Tarawa", 571),
        new("Pacific/Wallis", "Pacific/Tarawa", 572),
        new("Pacific/Yap", "Pacific/Port_Moresby", 573),
        new("Poland", "Europe/Warsaw", 574),
        new("Portugal", "Europe/Lisbon", 575),
        new("ROC", "Asia/Taipei", 576),
        new("ROK", "Asia/Seoul", 577),
        new("Singapore", "Asia/Singapore", 578),
        new("Turkey", "Europe/Istanbul", 579),
        new("UCT", "Etc/UTC", 580),
        new("US/Alaska", "America/Anchorage", 581),
        new("US/Aleutian", "America/Adak", 582),
        new("US/Arizona", "America/Phoenix", 583),
        new("US/Central", "America/Chicago", 584),
        new("US/East-Indiana", "America/Indiana/Indianapolis", 585),
        new("US/Eastern", "America/New_York", 586),
        new("US/Hawaii", "Pacific/Honolulu", 587),
        new("US/Indiana-Starke", "America/Indiana/Knox", 588),
        new("US/Michigan", "America/Detroit", 589),
        new("US/Mountain", "America/Denver", 590),
        new("US/Pacific", "America/Los_Angeles", 591),
        new("US/Samoa", "Pacific/Pago_Pago", 592),
        new("UTC", "Etc/UTC", 593),
        new("Universal", "Etc/UTC", 594),
        new("W-SU", "Europe/Moscow", 595),
        new("WET", "Europe/Lisbon", 596),
        new("Zulu", "Etc/UTC", 597),
    ];

    // A catalog upgrade appends a version here. Historical versions and their
    // entries must never be replaced or removed: native ledger rows retain a
    // restrictive foreign key to the exact catalog version they recorded.
    // Adding a seed here is intentionally not a plug-and-play runtime write.
    // Its PostgreSQL migration must take ACCESS EXCLUSIVE locks on both catalog
    // tables, verify every historical version, drop both immutable triggers,
    // insert only the new version, and recreate the triggers in the same
    // migration transaction. This explicit provider-owned protocol keeps the
    // application role unable to mutate catalog history between migrations.
    public static IReadOnlyList<PropertyTimeZoneCatalogVersionSeed>
        AllVersions
    { get; } =
    [
        new(
            CurrentCatalogVersion,
            CurrentCanonicalIdsSha256,
            CanonicalIds,
            CurrentResolutionsSha256,
            Resolutions)
    ];

    public static IReadOnlyList<PropertyTimeZoneCatalogEntrySeed> AllEntries
    { get; } = AllVersions
            .SelectMany(version => version.CanonicalIds.Select(
                (timeZoneId, index) => new PropertyTimeZoneCatalogEntrySeed(
                    version.CatalogVersion,
                    timeZoneId,
                    index + 1)))
            .ToArray();

    public static IReadOnlyList<PropertyTimeZoneCatalogResolutionSeed>
        AllResolutions
    { get; } = AllVersions
            .SelectMany(version => version.Resolutions.Select(resolution =>
                new PropertyTimeZoneCatalogResolutionSeed(
                    version.CatalogVersion,
                    resolution.RequestedTimeZoneId,
                    resolution.CanonicalTimeZoneId,
                    resolution.Ordinal)))
            .ToArray();
}

internal sealed record PropertyTimeZoneCatalogVersionSeed(
    string CatalogVersion,
    string CanonicalIdsSha256,
    IReadOnlyList<string> CanonicalIds,
    string ResolutionsSha256,
    IReadOnlyList<PropertyTimeZoneCatalogResolutionVersionEntrySeed>
        Resolutions);

internal sealed record PropertyTimeZoneCatalogEntrySeed(
    string CatalogVersion,
    string TimeZoneId,
    int Ordinal);

internal sealed record PropertyTimeZoneCatalogResolutionVersionEntrySeed(
    string RequestedTimeZoneId,
    string CanonicalTimeZoneId,
    int Ordinal);

internal sealed record PropertyTimeZoneCatalogResolutionSeed(
    string CatalogVersion,
    string RequestedTimeZoneId,
    string CanonicalTimeZoneId,
    int Ordinal);
