// <auto-generated />
using System;
using BunkFy.Modules.Properties.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BunkFy.Modules.Properties.Persistence.PostgreSqlMigrations.Migrations
{
    [DbContext(typeof(PropertiesDbContext))]
    [Migration("20260807184007_AddPropertyDetailsUpdateOperations")]
    partial class AddPropertyDetailsUpdateOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("properties")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BunkFy.Modules.Properties.Domain.Aggregates.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ProcessingState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<long>("ProjectionOrdinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProjectionOrdinal"));

                    b.Property<DateTimeOffset?>("RetiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("Id");

                    b.HasIndex("ProjectionOrdinal")
                        .IsUnique();

                    b.HasIndex("ScopeId", "Code")
                        .IsUnique();

                    b.ToTable("properties", "properties", t =>
                        {
                            t.HasCheckConstraint("CK_properties_governance_binding", "(\"ProcessingState\" = 1 AND \"OperatingCountryCode\" IS NULL AND \"JurisdictionPolicyId\" IS NULL AND \"JurisdictionPolicyVersion\" IS NULL AND \"DataRegionId\" IS NULL AND \"TransferProfileId\" IS NULL AND \"RetentionPolicyId\" IS NULL AND \"RetentionPolicyVersion\" IS NULL AND \"PolicyContentSha256\" IS NULL AND \"PolicyEffectiveAtUtc\" IS NULL AND \"PolicyExpiresAtUtc\" IS NULL AND \"PolicyActivatedAtUtc\" IS NULL) OR (\"ProcessingState\" IN (2, 3) AND \"OperatingCountryCode\" IS NOT NULL AND \"JurisdictionPolicyId\" IS NOT NULL AND \"JurisdictionPolicyVersion\" IS NOT NULL AND \"DataRegionId\" IS NOT NULL AND \"TransferProfileId\" IS NOT NULL AND \"RetentionPolicyId\" IS NOT NULL AND \"RetentionPolicyVersion\" IS NOT NULL AND \"PolicyContentSha256\" IS NOT NULL AND \"PolicyEffectiveAtUtc\" IS NOT NULL AND \"PolicyExpiresAtUtc\" IS NOT NULL AND \"PolicyActivatedAtUtc\" IS NOT NULL AND \"JurisdictionPolicyVersion\" > 0 AND \"RetentionPolicyVersion\" > 0 AND char_length(\"OperatingCountryCode\") = 2 AND char_length(\"PolicyContentSha256\") = 64 AND \"PolicyEffectiveAtUtc\" < \"PolicyExpiresAtUtc\" AND \"PolicyActivatedAtUtc\" >= \"PolicyEffectiveAtUtc\" AND \"PolicyActivatedAtUtc\" < \"PolicyExpiresAtUtc\")");

                            t.HasCheckConstraint("CK_properties_processing_state", "\"ProcessingState\" BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Properties.Domain.Aggregates.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuildingLabel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FloorLabel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RetiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("Id");

                    b.HasIndex("ScopeId", "PropertyId", "Name")
                        .IsUnique();

                    b.ToTable("rooms", "properties");
                });

            modelBuilder.Entity("BunkFy.Modules.Properties.Persistence.PropertiesTenantRevision", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("DestroyCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DestroyOperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestroyRequestSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("DestroyStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LifecycleStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("ScopeId");

                    b.ToTable("tenant_revisions", "properties", t =>
                        {
                            t.HasCheckConstraint("CK_properties_tenant_revision_lifecycle", "(\"LifecycleStatus\" = 1 AND \"DestroyOperationId\" IS NULL AND \"DestroyRequestSha256\" IS NULL AND \"DestroyStartedAtUtc\" IS NULL AND \"DestroyCompletedAtUtc\" IS NULL) OR (\"LifecycleStatus\" = 2 AND \"DestroyOperationId\" IS NOT NULL AND \"DestroyRequestSha256\" IS NOT NULL AND \"DestroyStartedAtUtc\" IS NOT NULL AND \"DestroyCompletedAtUtc\" IS NULL) OR (\"LifecycleStatus\" = 3 AND \"DestroyOperationId\" IS NOT NULL AND \"DestroyRequestSha256\" IS NOT NULL AND \"DestroyStartedAtUtc\" IS NOT NULL AND \"DestroyCompletedAtUtc\" >= \"DestroyStartedAtUtc\")");

                            t.HasCheckConstraint("CK_properties_tenant_revision_positive", "\"Revision\" > 0");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Properties.Persistence.PropertyGovernanceRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DecisionReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<long>("PropertyVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId", "PropertyId", "OccurredAtUtc");

                    b.HasIndex("ScopeId", "PropertyId", "PropertyVersion")
                        .IsUnique();

                    b.ToTable("property_governance_revisions", "properties", t =>
                        {
                            t.HasCheckConstraint("CK_property_governance_revision_action", "\"Action\" BETWEEN 1 AND 4");

                            t.HasCheckConstraint("CK_property_governance_revision_version", "\"PropertyVersion\" >= 2");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Properties.Persistence.PropertyMutationOperation", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExpectedVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ResultProcessingStatus")
                        .HasColumnType("integer");

                    b.Property<int>("ResultStatus")
                        .HasColumnType("integer");

                    b.Property<long>("ResultVersion")
                        .HasColumnType("bigint");

                    b.HasKey("ScopeId", "PropertyId", "Id");

                    b.HasIndex("ScopeId", "CompletedAtUtc", "Id");

                    b.ToTable("property_mutation_operations", "properties", t =>
                        {
                            t.HasCheckConstraint("CK_properties_property_mutation_operations_fingerprint", "char_length(\"RequestFingerprint\") = 64 AND \"RequestFingerprint\" ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("CK_properties_property_mutation_operations_kind", "\"Kind\" = 1");

                            t.HasCheckConstraint("CK_properties_property_mutation_operations_processing", "\"ResultProcessingStatus\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_properties_property_mutation_operations_status", "\"ResultStatus\" IN (1, 2)");

                            t.HasCheckConstraint("CK_properties_property_mutation_operations_versions", "\"ExpectedVersion\" > 0 AND \"ResultVersion\" >= \"ExpectedVersion\" AND \"ResultVersion\" <= \"ExpectedVersion\" + 1");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Properties.Persistence.PropertyOperationLock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasAlternateKey("ScopeId", "Id");

                    b.HasIndex("ScopeId", "PropertyId")
                        .IsUnique();

                    b.ToTable("property_operation_locks", "properties", t =>
                        {
                            t.HasCheckConstraint("CK_property_operation_locks_coordinate", "\"Id\" = \"PropertyId\"");

                            t.HasCheckConstraint("CK_property_operation_locks_revision", "\"Revision\" >= 1");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Properties.Persistence.RoomOperationLock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasAlternateKey("ScopeId", "Id");

                    b.HasIndex("ScopeId", "RoomId")
                        .IsUnique();

                    b.ToTable("room_operation_locks", "properties", t =>
                        {
                            t.HasCheckConstraint("CK_room_operation_locks_coordinate", "\"Id\" = \"RoomId\"");

                            t.HasCheckConstraint("CK_room_operation_locks_revision", "\"Revision\" >= 1");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Properties.Persistence.TenantTermination.PropertiesTenantDestroyOperation", b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<int>("BatchSize")
                        .HasColumnType("integer");

                    b.Property<int>("CompletedBatchCount")
                        .HasColumnType("integer");

                    b.Property<int>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<int>("ProofVersion")
                        .HasColumnType("integer");

                    b.Property<string>("RemovalProofSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<long>("RemovedRecordCount")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<long>("ResultingRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("SelectedRevision")
                        .HasColumnType("bigint");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OperationId");

                    b.HasIndex("ScopeId")
                        .IsUnique();

                    b.ToTable("tenant_destroy_operations", "properties", t =>
                        {
                            t.HasCheckConstraint("CK_properties_tenant_destroy_operation_batch", "\"BatchSize\" BETWEEN 1 AND 500");

                            t.HasCheckConstraint("CK_properties_tenant_destroy_operation_progress", "\"Stage\" BETWEEN 1 AND 11 AND \"RemovedRecordCount\" >= 0 AND \"CompletedBatchCount\" >= 0 AND \"ProofVersion\" = 1 AND \"ConcurrencyVersion\" >= 1");

                            t.HasCheckConstraint("CK_properties_tenant_destroy_operation_revisions", "\"SelectedRevision\" >= 0 AND \"ResultingRevision\" = \"SelectedRevision\" + 1");

                            t.HasCheckConstraint("CK_properties_tenant_destroy_operation_times", "\"UpdatedAtUtc\" >= \"StartedAtUtc\"");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Properties.Persistence.TenantTermination.PropertiesTenantDestroyReceipt", b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<int>("BatchSize")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompletedBatchCount")
                        .HasColumnType("integer");

                    b.Property<string>("RemovalProofSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<int>("RemovalProofVersion")
                        .HasColumnType("integer");

                    b.Property<long>("RemovedRecordCount")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<long>("ResultingRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("SelectedRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OperationId");

                    b.HasIndex("ScopeId")
                        .IsUnique();

                    b.ToTable("tenant_destroy_receipts", "properties", t =>
                        {
                            t.HasCheckConstraint("CK_properties_tenant_destroy_receipt_progress", "((\"RemovedRecordCount\" = 0 AND \"CompletedBatchCount\" = 0) OR (\"RemovedRecordCount\" > 0 AND \"CompletedBatchCount\" > 0)) AND \"BatchSize\" BETWEEN 1 AND 500 AND \"RemovalProofVersion\" = 1");

                            t.HasCheckConstraint("CK_properties_tenant_destroy_receipt_revisions", "\"SelectedRevision\" >= 0 AND \"ResultingRevision\" = \"SelectedRevision\" + 1");

                            t.HasCheckConstraint("CK_properties_tenant_destroy_receipt_times", "\"CompletedAtUtc\" >= \"StartedAtUtc\"");
                        });
                });

            modelBuilder.Entity("Gma.Framework.Messaging.Infrastructure.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Handler")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessingStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ScopeId");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id", "Handler");

                    b.HasIndex("Handler", "Status");

                    b.HasIndex("Status", "ProcessedAtUtc");

                    b.ToTable("inbox_messages", "properties");
                });

            modelBuilder.Entity("Gma.Framework.Messaging.Infrastructure.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ScopeId");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "NextAttemptAtUtc", "LockedUntilUtc", "CreatedAtUtc");

                    b.ToTable("outbox_messages", "properties");
                });

            modelBuilder.Entity("BunkFy.Modules.Properties.Domain.Aggregates.Property", b =>
                {
                    b.OwnsMany("BunkFy.Modules.Properties.Domain.ValueObjects.PropertyGovernanceAcknowledgement", "GovernanceAcknowledgements", b1 =>
                        {
                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AcknowledgementId")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<int>("AcknowledgementVersion")
                                .HasColumnType("integer");

                            b1.HasKey("PropertyId", "AcknowledgementId", "AcknowledgementVersion");

                            b1.ToTable("property_governance_acknowledgements", "properties");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.OwnsOne("BunkFy.Modules.Properties.Domain.ValueObjects.PropertyGovernanceBinding", "GovernanceBinding", b1 =>
                        {
                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("ActivatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PolicyActivatedAtUtc");

                            b1.Property<string>("ContentSha256")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("PolicyContentSha256");

                            b1.Property<string>("DataRegionId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("DataRegionId");

                            b1.Property<string>("OperatingCountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("OperatingCountryCode");

                            b1.Property<DateTimeOffset>("PolicyEffectiveAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PolicyEffectiveAtUtc");

                            b1.Property<DateTimeOffset>("PolicyExpiresAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PolicyExpiresAtUtc");

                            b1.Property<string>("PolicyId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("JurisdictionPolicyId");

                            b1.Property<int>("PolicyVersion")
                                .HasColumnType("integer")
                                .HasColumnName("JurisdictionPolicyVersion");

                            b1.Property<string>("RetentionPolicyId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("RetentionPolicyId");

                            b1.Property<int>("RetentionPolicyVersion")
                                .HasColumnType("integer")
                                .HasColumnName("RetentionPolicyVersion");

                            b1.Property<string>("TransferProfileId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("TransferProfileId");

                            b1.HasKey("PropertyId");

                            b1.ToTable("properties", "properties");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.Navigation("GovernanceAcknowledgements");

                    b.Navigation("GovernanceBinding");
                });

            modelBuilder.Entity("BunkFy.Modules.Properties.Domain.Aggregates.Room", b =>
                {
                    b.HasOne("BunkFy.Modules.Properties.Domain.Aggregates.Property", null)
                        .WithMany()
                        .HasForeignKey("ScopeId", "PropertyId")
                        .HasPrincipalKey("ScopeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("BunkFy.Modules.Properties.Domain.Entities.Bed", "Beds", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("RetiredAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ScopeId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<int>("Status")
                                .HasColumnType("integer");

                            b1.Property<DateTimeOffset?>("UpdatedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<long>("Version")
                                .IsConcurrencyToken()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasDefaultValue(1L);

                            b1.HasKey("Id");

                            b1.HasIndex("RoomId");

                            b1.HasIndex("ScopeId", "RoomId", "Label")
                                .IsUnique();

                            b1.ToTable("beds", "properties");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.Navigation("Beds");
                });

            modelBuilder.Entity("BunkFy.Modules.Properties.Persistence.PropertyGovernanceRevision", b =>
                {
                    b.HasOne("BunkFy.Modules.Properties.Domain.Aggregates.Property", null)
                        .WithMany()
                        .HasForeignKey("ScopeId", "PropertyId")
                        .HasPrincipalKey("ScopeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("BunkFy.Modules.Properties.Persistence.PropertyGovernanceRevisionCoordinatesRecord", "Current", b1 =>
                        {
                            b1.Property<Guid>("PropertyGovernanceRevisionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AcknowledgementSetSha256")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("CurrentAcknowledgementSetSha256");

                            b1.Property<string>("ContentSha256")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("CurrentPolicyContentSha256");

                            b1.Property<string>("DataRegionId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("CurrentDataRegionId");

                            b1.Property<string>("OperatingCountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("CurrentOperatingCountryCode");

                            b1.Property<string>("PolicyId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("CurrentJurisdictionPolicyId");

                            b1.Property<int>("PolicyVersion")
                                .HasColumnType("integer")
                                .HasColumnName("CurrentJurisdictionPolicyVersion");

                            b1.Property<string>("RetentionPolicyId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("CurrentRetentionPolicyId");

                            b1.Property<int>("RetentionPolicyVersion")
                                .HasColumnType("integer")
                                .HasColumnName("CurrentRetentionPolicyVersion");

                            b1.Property<string>("TransferProfileId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("CurrentTransferProfileId");

                            b1.HasKey("PropertyGovernanceRevisionId");

                            b1.ToTable("property_governance_revisions", "properties");

                            b1.WithOwner()
                                .HasForeignKey("PropertyGovernanceRevisionId");
                        });

                    b.OwnsOne("BunkFy.Modules.Properties.Persistence.PropertyGovernanceRevisionCoordinatesRecord", "Previous", b1 =>
                        {
                            b1.Property<Guid>("PropertyGovernanceRevisionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AcknowledgementSetSha256")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("PreviousAcknowledgementSetSha256");

                            b1.Property<string>("ContentSha256")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("PreviousPolicyContentSha256");

                            b1.Property<string>("DataRegionId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("PreviousDataRegionId");

                            b1.Property<string>("OperatingCountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("PreviousOperatingCountryCode");

                            b1.Property<string>("PolicyId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("PreviousJurisdictionPolicyId");

                            b1.Property<int>("PolicyVersion")
                                .HasColumnType("integer")
                                .HasColumnName("PreviousJurisdictionPolicyVersion");

                            b1.Property<string>("RetentionPolicyId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("PreviousRetentionPolicyId");

                            b1.Property<int>("RetentionPolicyVersion")
                                .HasColumnType("integer")
                                .HasColumnName("PreviousRetentionPolicyVersion");

                            b1.Property<string>("TransferProfileId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("PreviousTransferProfileId");

                            b1.HasKey("PropertyGovernanceRevisionId");

                            b1.ToTable("property_governance_revisions", "properties");

                            b1.WithOwner()
                                .HasForeignKey("PropertyGovernanceRevisionId");
                        });

                    b.Navigation("Current");

                    b.Navigation("Previous");
                });

            modelBuilder.Entity("BunkFy.Modules.Properties.Persistence.PropertyMutationOperation", b =>
                {
                    b.HasOne("BunkFy.Modules.Properties.Domain.Aggregates.Property", null)
                        .WithMany()
                        .HasForeignKey("ScopeId", "PropertyId")
                        .HasPrincipalKey("ScopeId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
