// <auto-generated />
using System;
using BunkFy.Modules.Workspaces.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BunkFy.Modules.Workspaces.Persistence.PostgreSqlMigrations.Migrations
{
    [DbContext(typeof(WorkspacesDbContext))]
    [Migration("20260730133835_AddWorkspaceStaffOnboardingProcessingRestrictions")]
    partial class AddWorkspaceStaffOnboardingProcessingRestrictions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workspaces")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BunkFy.Modules.Workspaces.Domain.DataRights.WorkspaceStaffOnboardingCorrectionReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<long>("ApprovalRevision")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChangedFieldsMask")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CompletionEventId")
                        .HasColumnType("uuid");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer");

                    b.Property<long>("CurrentRecordVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("SelectedRecordVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("ScopeId", "Id");

                    b.HasIndex("ScopeId", "ApplicantEventId")
                        .IsUnique();

                    b.HasIndex("ScopeId", "CompletionEventId")
                        .IsUnique();

                    b.HasIndex("ScopeId", "ExecutionId")
                        .IsUnique();

                    b.HasIndex("ScopeId", "CaseId", "ApprovalRevision");

                    b.HasIndex("ScopeId", "ApplicationId", "CompletedAtUtc", "Id");

                    b.ToTable("staff_onboarding_correction_receipts", "workspaces", t =>
                        {
                            t.HasCheckConstraint("CK_workspaces_staff_onboarding_correction_receipts_approval", "\"ApprovalRevision\" >= 1");

                            t.HasCheckConstraint("CK_workspaces_staff_onboarding_correction_receipts_contract", "\"ContractVersion\" = 1");

                            t.HasCheckConstraint("CK_workspaces_staff_onboarding_correction_receipts_digest", "char_length(\"RequestSha256\") = 64");

                            t.HasCheckConstraint("CK_workspaces_staff_onboarding_correction_receipts_fields", "\"ChangedFieldsMask\" BETWEEN 1 AND 127");

                            t.HasCheckConstraint("CK_workspaces_staff_onboarding_correction_receipts_versions", "\"SelectedRecordVersion\" >= 1 AND \"CurrentRecordVersion\" = \"SelectedRecordVersion\" + 1");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Workspaces.Domain.DataRights.WorkspaceStaffOnboardingProcessingRestriction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AppliedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("ApplyApprovalRevision")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ApplyCaseId")
                        .HasColumnType("uuid");

                    b.Property<long>("ApplySelectedOnboardingVersion")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReleaseApprovalRevision")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ReleaseCaseId")
                        .HasColumnType("uuid");

                    b.Property<long?>("ReleaseSelectedOnboardingVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReleasedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("ScopeId", "Id");

                    b.HasIndex("ScopeId", "ApplicationId", "ApplyCaseId", "ApplyApprovalRevision")
                        .IsUnique();

                    b.HasIndex("ScopeId", "ApplicationId", "ReleaseCaseId", "ReleaseApprovalRevision")
                        .IsUnique()
                        .HasDatabaseName("IX_staff_onboarding_processing_restrictions_ScopeId_Applicati~1");

                    b.HasIndex("ScopeId", "ApplicationId", "Status", "AppliedAtUtc")
                        .HasDatabaseName("IX_staff_onboarding_processing_restrictions_ScopeId_Applicati~2");

                    b.ToTable("staff_onboarding_processing_restrictions", "workspaces", t =>
                        {
                            t.HasCheckConstraint("CK_ws_onboarding_restrictions_apply", "\"ApplyApprovalRevision\" >= 1 AND \"ApplySelectedOnboardingVersion\" >= 1");

                            t.HasCheckConstraint("CK_ws_onboarding_restrictions_lifecycle", "(\"Status\" = 1 AND \"ReleaseCaseId\" IS NULL AND \"ReleaseApprovalRevision\" IS NULL AND \"ReleaseSelectedOnboardingVersion\" IS NULL AND \"ReleasedBy\" IS NULL AND \"ReleasedAtUtc\" IS NULL AND \"Version\" = 1) OR (\"Status\" = 2 AND \"ReleaseCaseId\" IS NOT NULL AND \"ReleaseApprovalRevision\" >= 1 AND \"ReleaseSelectedOnboardingVersion\" >= 1 AND \"ReleasedBy\" IS NOT NULL AND \"ReleasedAtUtc\" IS NOT NULL AND \"ReleasedAtUtc\" >= \"AppliedAtUtc\" AND \"Version\" >= 2)");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Workspaces.Domain.DataRights.WorkspaceStaffOnboardingProcessingRestrictionProjection", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveRestrictionCount")
                        .HasColumnType("integer");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRestricted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastTransitionAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ProjectionOrdinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProjectionOrdinal"));

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("ScopeId", "ApplicationId");

                    b.HasIndex("ProjectionOrdinal")
                        .IsUnique();

                    b.HasIndex("ScopeId", "IsRestricted", "ApplicationId");

                    b.ToTable("staff_onboarding_processing_restriction_state", "workspaces", t =>
                        {
                            t.HasCheckConstraint("CK_ws_onboarding_restriction_contract", "\"ContractVersion\" >= 1");

                            t.HasCheckConstraint("CK_ws_onboarding_restriction_revision", "\"Revision\" >= 0");

                            t.HasCheckConstraint("CK_ws_onboarding_restriction_state", "(\"ActiveRestrictionCount\" = 0 AND NOT \"IsRestricted\") OR (\"ActiveRestrictionCount\" > 0 AND \"IsRestricted\")");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Workspaces.Domain.DataRights.WorkspaceStaffOnboardingProcessingRestrictionReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<long>("ApprovalRevision")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EffectiveRestricted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RestrictionId")
                        .HasColumnType("uuid");

                    b.Property<long>("ResultingProjectionRevision")
                        .HasColumnType("bigint");

                    b.Property<long>("ResultingRestrictionVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("SelectedOnboardingVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("ScopeId", "Id");

                    b.HasIndex("ScopeId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ScopeId", "ApplicationId", "CompletedAtUtc");

                    b.HasIndex("ScopeId", "CaseId", "ApprovalRevision");

                    b.ToTable("staff_onboarding_processing_restriction_receipts", "workspaces", t =>
                        {
                            t.HasCheckConstraint("CK_ws_onboarding_restriction_receipt_versions", "\"ApprovalRevision\" >= 1 AND \"SelectedOnboardingVersion\" >= 1 AND \"ResultingProjectionRevision\" >= 1 AND ((\"Action\" = 1 AND \"ResultingRestrictionVersion\" = 1 AND \"EffectiveRestricted\") OR (\"Action\" = 2 AND \"ResultingRestrictionVersion\" >= 2))");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Workspaces.Domain.WorkspaceStaffAccessPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBySubjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("LastChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProfileKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("SourceExpiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SourceKind")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId", "CreatedBySubjectId", "Id");

                    b.HasIndex("ScopeId", "SourceKind", "SourceExpiredAtUtc", "Id");

                    b.HasIndex("ScopeId", "Status", "CreatedAtUtc", "Id");

                    b.ToTable("staff_access_plans", "workspaces", t =>
                        {
                            t.HasCheckConstraint("CK_staff_access_plans_expiry_authority", "\"Status\" <> 4 OR \"SourceExpiredAtUtc\" IS NOT NULL");

                            t.HasCheckConstraint("CK_staff_access_plans_source", "\"SourceKind\" IN (1, 2)");

                            t.HasCheckConstraint("CK_staff_access_plans_status", "\"Status\" IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_staff_access_plans_version", "\"Version\" >= 1");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Workspaces.Domain.WorkspaceStaffAccessPlanProperty", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.HasKey("ScopeId", "PlanId", "PropertyId");

                    b.HasIndex("ScopeId", "PropertyId", "PlanId");

                    b.ToTable("staff_access_plan_properties", "workspaces");
                });

            modelBuilder.Entity("BunkFy.Modules.Workspaces.Domain.WorkspaceStaffAccessProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveOn")
                        .HasColumnType("date");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("LastChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("TargetStaffVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("TargetState")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("ScopeId", "Id");

                    b.HasIndex("ScopeId", "RequestedBy", "Id");

                    b.HasIndex("ScopeId", "StaffMemberId", "TargetStaffVersion")
                        .IsUnique();

                    b.HasIndex("ScopeId", "StaffMemberId", "State", "CreatedAtUtc");

                    b.HasIndex("ScopeId", "SubjectId", "State", "Id");

                    b.ToTable("staff_access_processes", "workspaces", t =>
                        {
                            t.HasCheckConstraint("CK_staff_access_process_staff_version", "\"TargetStaffVersion\" >= 2");

                            t.HasCheckConstraint("CK_staff_access_process_state", "\"State\" BETWEEN 1 AND 4");

                            t.HasCheckConstraint("CK_staff_access_process_target", "\"TargetState\" BETWEEN 1 AND 3");

                            t.HasCheckConstraint("CK_staff_access_process_version", "\"Version\" >= 1");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Workspaces.Domain.WorkspaceStaffOnboarding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<long?>("ClaimVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmployeeNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("LastChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LegalName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourceKind")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("VerifiedAccountEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("WorkEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("WorkPhone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasAlternateKey("ScopeId", "Id");

                    b.HasIndex("ScopeId", "ClaimId")
                        .IsUnique();

                    b.HasIndex("ScopeId", "StaffMemberId", "Id")
                        .HasFilter("\"StaffMemberId\" IS NOT NULL");

                    b.HasIndex("ScopeId", "SourceKind", "SourceId", "SubjectId")
                        .IsUnique();

                    b.HasIndex("ScopeId", "Status", "CreatedAtUtc", "Id");

                    b.HasIndex("ScopeId", "SubjectId", "Status", "Id");

                    b.ToTable("staff_onboarding_applications", "workspaces", t =>
                        {
                            t.HasCheckConstraint("CK_staff_onboarding_claim", "(\"ClaimId\" IS NULL AND \"ClaimVersion\" IS NULL) OR (\"ClaimId\" IS NOT NULL AND \"ClaimVersion\" > 0)");

                            t.HasCheckConstraint("CK_staff_onboarding_pending_profile", "\"Status\" IN (5, 7, 8, 9) OR (\"VerifiedAccountEmail\" IS NOT NULL AND \"DisplayName\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_staff_onboarding_source", "\"SourceKind\" IN (1, 2)");

                            t.HasCheckConstraint("CK_staff_onboarding_staff", "\"Status\" NOT IN (4, 5) OR \"StaffMemberId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_staff_onboarding_status", "\"Status\" BETWEEN 1 AND 9");

                            t.HasCheckConstraint("CK_staff_onboarding_terminal_redaction", "\"Status\" NOT IN (5, 7, 8, 9) OR (\"VerifiedAccountEmail\" IS NULL AND \"DisplayName\" IS NULL AND \"LegalName\" IS NULL AND \"WorkEmail\" IS NULL AND \"WorkPhone\" IS NULL AND \"EmployeeNumber\" IS NULL AND \"JobTitle\" IS NULL AND \"Department\" IS NULL)");

                            t.HasCheckConstraint("CK_staff_onboarding_version", "\"Version\" >= 1");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Workspaces.Domain.WorkspaceStaffRetentionCorrelationReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessPlanRecordsScrubbed")
                        .HasColumnType("integer");

                    b.Property<int>("AccessProcessRecordsScrubbed")
                        .HasColumnType("integer");

                    b.Property<string>("CanonicalSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid");

                    b.Property<int>("OnboardingRecordsScrubbed")
                        .HasColumnType("integer");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("SelectedStaffVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasAlternateKey("ScopeId", "Id");

                    b.HasIndex("ScopeId", "ExecutionId", "Id");

                    b.HasIndex("ScopeId", "StaffMemberId", "SelectedStaffVersion")
                        .IsUnique();

                    b.ToTable("staff_retention_correlation_receipts", "workspaces", t =>
                        {
                            t.HasCheckConstraint("CK_staff_retention_correlation_receipt_contract", "\"ContractVersion\" = 1");

                            t.HasCheckConstraint("CK_staff_retention_correlation_receipt_counts", "\"OnboardingRecordsScrubbed\" >= 0 AND \"AccessProcessRecordsScrubbed\" >= 0 AND \"AccessPlanRecordsScrubbed\" >= 0");

                            t.HasCheckConstraint("CK_staff_retention_correlation_receipt_hash", "char_length(\"CanonicalSha256\") = 64");

                            t.HasCheckConstraint("CK_staff_retention_correlation_receipt_version", "\"SelectedStaffVersion\" > 0");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Workspaces.Persistence.WorkspaceProjectionRebuildCheckpoint", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProjectionName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cursor")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("FailedCount")
                        .HasColumnType("bigint");

                    b.Property<long>("ProcessedCount")
                        .HasColumnType("bigint");

                    b.Property<int>("ProjectionVersion")
                        .HasColumnType("integer");

                    b.Property<long>("SkippedCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("WrittenCount")
                        .HasColumnType("bigint");

                    b.HasKey("ScopeId", "ProjectionName", "RunId");

                    b.ToTable("projection_rebuild_checkpoints", "workspaces");
                });

            modelBuilder.Entity("BunkFy.Modules.Workspaces.Persistence.WorkspacePropertyProjection", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("ScopeId", "Id");

                    b.HasIndex("ScopeId", "Status", "Id");

                    b.ToTable("property_projection", "workspaces", t =>
                        {
                            t.HasCheckConstraint("CK_workspaces_property_projection_version", "\"Version\" >= 1");
                        });
                });

            modelBuilder.Entity("Gma.Framework.Messaging.Infrastructure.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Handler")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessingStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ScopeId");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id", "Handler");

                    b.HasIndex("Handler", "Status");

                    b.HasIndex("Status", "ProcessedAtUtc");

                    b.ToTable("inbox_messages", "workspaces");
                });

            modelBuilder.Entity("Gma.Framework.Messaging.Infrastructure.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ScopeId");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "NextAttemptAtUtc", "LockedUntilUtc", "CreatedAtUtc");

                    b.ToTable("outbox_messages", "workspaces");
                });

            modelBuilder.Entity("BunkFy.Modules.Workspaces.Domain.WorkspaceStaffAccessPlanProperty", b =>
                {
                    b.HasOne("BunkFy.Modules.Workspaces.Domain.WorkspaceStaffAccessPlan", null)
                        .WithMany("Properties")
                        .HasForeignKey("ScopeId", "PlanId")
                        .HasPrincipalKey("ScopeId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BunkFy.Modules.Workspaces.Domain.WorkspaceStaffAccessProcess", b =>
                {
                    b.OwnsMany("BunkFy.Modules.Workspaces.Domain.WorkspaceStaffAccessProfileSnapshot", "ProfileSnapshots", b1 =>
                        {
                            b1.Property<Guid>("ProcessId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AssignmentScope")
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)");

                            b1.HasKey("ProcessId", "ProfileId", "AssignmentScope");

                            b1.ToTable("staff_access_profile_snapshots", "workspaces");

                            b1.WithOwner()
                                .HasForeignKey("ProcessId");
                        });

                    b.Navigation("ProfileSnapshots");
                });

            modelBuilder.Entity("BunkFy.Modules.Workspaces.Domain.WorkspaceStaffAccessPlan", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
