<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><NoWarn>$(NoWarn);CA1861;IDE0065;IDE0161;IDE0300</NoWarn></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../BunkFy.Modules.Stations.Persistence/BunkFy.Modules.Stations.Persistence.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
</Project>

