// <auto-generated />
using System;
using BunkFy.Modules.Stations.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BunkFy.Modules.Stations.Persistence.PostgreSqlMigrations.Migrations
{
    [DbContext(typeof(StationsDbContext))]
    [Migration("20260920020000_AddStationManagementPrerequisites")]
    partial class AddStationManagementPrerequisites
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("stations")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BunkFy.Modules.Stations.Domain.Station", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("ScopeId", "Id");

                    b.ToTable("stations", "stations", t =>
                        {
                            t.HasCheckConstraint("CK_station_version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Stations.Domain.StationBrowserSession", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActorAbsoluteExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ActorIdleExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ActorSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("AttemptWindowStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AuthorityKind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CooldownUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CredentialDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("CredentialRevision")
                        .HasColumnType("bigint");

                    b.Property<long>("ExternalEpoch")
                        .HasColumnType("bigint");

                    b.Property<long>("Generation")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<long?>("GrantRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PairingExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.HasKey("ScopeId", "Id");

                    b.HasIndex("CredentialDigest")
                        .IsUnique();

                    b.HasIndex("ScopeId", "StaffMemberId");

                    b.HasIndex("ScopeId", "StationId", "PropertyId");

                    b.ToTable("browser_sessions", "stations", t =>
                        {
                            t.HasCheckConstraint("CK_browser_actor", "(\"StaffMemberId\" IS NULL AND \"ActorSessionId\" IS NULL AND \"AuthorityKind\" = 0 AND \"CredentialRevision\" IS NULL AND \"GrantRevision\" IS NULL AND \"ActorIdleExpiresAtUtc\" IS NULL AND \"ActorAbsoluteExpiresAtUtc\" IS NULL) OR (\"StaffMemberId\" IS NOT NULL AND \"ActorSessionId\" IS NOT NULL AND \"CredentialRevision\" IS NOT NULL AND \"CredentialRevision\" > 0 AND \"ActorIdleExpiresAtUtc\" IS NOT NULL AND \"ActorAbsoluteExpiresAtUtc\" IS NOT NULL AND ((\"AuthorityKind\" = 1 AND \"GrantRevision\" IS NULL) OR (\"AuthorityKind\" = 2 AND \"GrantRevision\" IS NOT NULL AND \"GrantRevision\" > 0)))");

                            t.HasCheckConstraint("CK_browser_attempts", "\"AttemptCount\" >= 0");

                            t.HasCheckConstraint("CK_browser_lifetime", "\"PairingExpiresAtUtc\" > \"IssuedAtUtc\" AND \"ExternalEpoch\" > 0 AND \"Generation\" > 0");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Stations.Domain.StationOperationReceipt", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BrowserSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("Generation")
                        .HasColumnType("bigint");

                    b.Property<int>("IssuerKind")
                        .HasColumnType("integer");

                    b.Property<Guid?>("IssuerSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("IssuerSubjectId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<long?>("ResourceVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("RetryAfterUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SetupGrantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StationId")
                        .HasColumnType("uuid");

                    b.HasKey("ScopeId", "Id");

                    b.ToTable("operation_receipts", "stations", t =>
                        {
                            t.HasCheckConstraint("CK_receipt_issuer", "(\"IssuerKind\" = 0 AND \"IssuerSubjectId\" IS NULL) OR (\"IssuerKind\" IN (1,2) AND \"IssuerSubjectId\" IS NOT NULL AND length(\"IssuerSubjectId\") = 36)");

                            t.HasCheckConstraint("CK_receipt_kind", "\"Kind\" BETWEEN 1 AND 15 AND \"Outcome\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_receipt_session", "\"IssuerSessionId\" IS NULL OR (\"IssuerKind\" IN (1,2) AND \"Kind\" IN (1,9,15) AND \"IssuerSessionId\" <> '00000000-0000-0000-0000-000000000000'::uuid)");
                            t.HasCheckConstraint("CK_receipt_own_pin", "\"Kind\" <> 15 OR (\"IssuerKind\" = 2 AND \"IssuerSubjectId\" IS NOT NULL AND \"IssuerSessionId\" IS NOT NULL AND \"IssuerSessionId\" <> '00000000-0000-0000-0000-000000000000'::uuid AND \"PropertyId\" IS NOT NULL AND \"PropertyId\" <> '00000000-0000-0000-0000-000000000000'::uuid AND \"StaffMemberId\" IS NOT NULL AND \"StaffMemberId\" <> '00000000-0000-0000-0000-000000000000'::uuid AND \"ResourceVersion\" IS NOT NULL AND \"ResourceVersion\" >= 0 AND (\"Outcome\" <> 1 OR \"ResourceVersion\" > 0))");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Stations.Domain.StationSetupGrant", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AssuranceExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AuthorityKind")
                        .HasColumnType("integer");

                    b.Property<Guid>("BrowserSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExpectedCredentialRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("ExpectedEnrollmentAuthSubjectId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ExpectedEnrollmentAuthorityKind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IssuerKind")
                        .HasColumnType("integer");

                    b.Property<string>("IssuerSubjectId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.HasKey("ScopeId", "Id");

                    b.HasIndex("ScopeId", "BrowserSessionId", "StationId", "PropertyId");

                    b.ToTable("setup_grants", "stations", t =>
                        {
                            t.HasCheckConstraint("CK_setup_enrollment", "(\"ExpectedEnrollmentAuthorityKind\" = 0 AND \"ExpectedEnrollmentAuthSubjectId\" IS NULL) OR (\"ExpectedEnrollmentAuthorityKind\" = \"AuthorityKind\" AND ((\"ExpectedEnrollmentAuthorityKind\" = 2 AND \"ExpectedEnrollmentAuthSubjectId\" IS NULL) OR (\"ExpectedEnrollmentAuthorityKind\" = 1 AND \"ExpectedEnrollmentAuthSubjectId\" IS NOT NULL AND length(btrim(\"ExpectedEnrollmentAuthSubjectId\")) > 0 AND \"ExpectedEnrollmentAuthSubjectId\" = btrim(\"ExpectedEnrollmentAuthSubjectId\"))))");

                            t.HasCheckConstraint("CK_setup_issuer", "(\"IssuerKind\" = 0 AND \"IssuerSubjectId\" IS NULL AND \"AssuranceExpiresAtUtc\" IS NULL) OR (\"IssuerKind\" IN (1,2) AND \"IssuerSubjectId\" IS NOT NULL AND length(\"IssuerSubjectId\") = 36 AND \"AssuranceExpiresAtUtc\" IS NOT NULL AND \"AssuranceExpiresAtUtc\" >= \"ExpiresAtUtc\" AND (\"IssuerKind\" = 1 OR (\"ExpectedEnrollmentAuthorityKind\" = 1 AND \"IssuerSubjectId\" = \"ExpectedEnrollmentAuthSubjectId\")))");

                            t.HasCheckConstraint("CK_setup_valid", "\"ExpiresAtUtc\" > \"CreatedAtUtc\" AND \"ExpectedCredentialRevision\" >= 0 AND \"AuthorityKind\" IN (1,2)");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Stations.Domain.StationStaffCheckInGrant", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.HasKey("ScopeId", "PropertyId", "StaffMemberId");

                    b.ToTable("staff_check_in_grants", "stations", t =>
                        {
                            t.HasCheckConstraint("CK_grant_revision", "\"Revision\" > 0");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Stations.Domain.StationStaffCredential", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<int>("AlgorithmVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CooldownUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnrollmentAuthSubjectId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("EnrollmentAuthorityKind")
                        .HasColumnType("integer");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FailureWindowStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Iterations")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PepperVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("character varying(88)");

                    b.Property<string>("Verifier")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)");

                    b.HasKey("ScopeId", "StaffMemberId");

                    b.ToTable("staff_credentials", "stations", t =>
                        {
                            t.HasCheckConstraint("CK_credential_enrollment", "(\"EnrollmentAuthorityKind\" IN (0,2) AND \"EnrollmentAuthSubjectId\" IS NULL) OR (\"EnrollmentAuthorityKind\" = 1 AND \"EnrollmentAuthSubjectId\" IS NOT NULL AND length(btrim(\"EnrollmentAuthSubjectId\")) > 0 AND \"EnrollmentAuthSubjectId\" = btrim(\"EnrollmentAuthSubjectId\"))");

                            t.HasCheckConstraint("CK_credential_failure", "\"FailureCount\" >= 0");

                            t.HasCheckConstraint("CK_credential_version", "\"Revision\" > 0 AND \"AlgorithmVersion\" = 1 AND \"Iterations\" = 600000");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Stations.Domain.StationStaffRegistration", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<long>("RosterReference")
                        .HasColumnType("bigint");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("ScopeId", "PropertyId", "StaffMemberId");

                    b.HasIndex("ScopeId", "PropertyId", "RosterReference")
                        .IsUnique();

                    b.ToTable("staff_registrations", "stations", t =>
                        {
                            t.HasCheckConstraint("CK_registration_version", "\"Version\" > 0 AND \"RosterReference\" > 0");
                        });
                });

            modelBuilder.Entity("BunkFy.Modules.Stations.Persistence.StationsTenantLifecycleState", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("Closed")
                        .HasColumnType("boolean");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("ScopeId");

                    b.ToTable("tenant_lifecycle", "stations");
                });

            modelBuilder.Entity("BunkFy.Modules.Stations.Domain.StationBrowserSession", b =>
                {
                    b.HasOne("BunkFy.Modules.Stations.Domain.Station", null)
                        .WithMany()
                        .HasForeignKey("ScopeId", "StationId", "PropertyId")
                        .HasPrincipalKey("ScopeId", "Id", "PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BunkFy.Modules.Stations.Domain.StationSetupGrant", b =>
                {
                    b.HasOne("BunkFy.Modules.Stations.Domain.StationBrowserSession", null)
                        .WithMany()
                        .HasForeignKey("ScopeId", "BrowserSessionId", "StationId", "PropertyId")
                        .HasPrincipalKey("ScopeId", "Id", "StationId", "PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
